<a href="https://colab.research.google.com/github/sheka00/data_analysis_in_python/blob/main/%D0%9A%D1%83%D0%BB%D0%B0%D0%BD%D1%87%D0%B5%D0%B5%D0%B2_%D0%95%D0%B2%D0%B3%D0%B5%D0%BD%D0%B8%D0%B9_%D0%A0%D0%98_200016_Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np

###Задание 1
проверьте тип объекта python_list
если это не numpy ndarray, то преобразуйте к нему
проверьте, что на выходе вы получили объект python_list желаемого типа

In [6]:
python_list = [1, 12, 13, 45, 76, 45, 98, 0]
print(type(python_list))

python_list = np.array(python_list)
print(type(python_list))

<class 'list'>
<class 'numpy.ndarray'>


###Задание 2
создайте одномерный массив numpy из 10 элементов заполненный числом 1.5

In [7]:
z = np.full((10), 1.5)
print(z)

[1.5 1.5 1.5 1.5 1.5 1.5 1.5 1.5 1.5 1.5]


###Задание 3
создайте двумерный массив numpy из 25 элементов заполненный числом 0

In [8]:
z = np.zeros((5, 5))
print(z)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


###Задание 4
создайте одномерный массив numpy из 12 элементов заполненный числом 1

In [9]:
ones = np.ones((12))
print(ones)

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


###Задание 5
преобразуйте массив из предыдущего задания к матрице 3 на 4
выведите размерность полученного массива

In [10]:
ones = ones.reshape(3,4)
print(ones.shape)


(3, 4)

###Задание 6
создайте матрицу 4 на 5 заполненную числами от 1 до 20
замените элемент в 3-й строке 4-м столбце на -99

In [11]:
Z = np.random.randint(1, 20, (4, 5))
print(Z)
Z[2,3] = -99
print(Z)

[[ 2 15  1  2 16]
 [ 6 18  5  3 19]
 [ 7 11  3  4  6]
 [ 5 19 11  8 19]]
[[  2  15   1   2  16]
 [  6  18   5   3  19]
 [  7  11   3 -99   6]
 [  5  19  11   8  19]]


###Задание 7
создайте вектор длинной 15 со случайными целыми числами в диапазоне от -10 до 10
сделайте реверс вектора

In [12]:
first = np.random.randint(-10, 10, 15)
print(first)
second = np.flip(first)
print(second)

[-10  -6   6 -10 -10   1   2   4   5 -10  -5   2  -3   7 -10]
[-10   7  -3   2  -5 -10   5   4   2   1 -10 -10   6  -6 -10]


###Задание 8
создайте матрицу 5 на 5 со случайными целыми числами в диапазоне от -15 до 15
замените отрицательные элементы на их квадраты

In [13]:
first = np.random.randint(-15, 15, (5,5))
print(first)

first = np.where(first > 0, first, first**2)
print(first)

[[ 12  -2  -6  10   7]
 [-10  -5   0  11   5]
 [ -2   4  -8  -1 -11]
 [ -7   8 -13 -11   9]
 [ 14  14  12   8  -6]]
[[ 12   4  36  10   7]
 [100  25   0  11   5]
 [  4   4  64   1 121]
 [ 49   8 169 121   9]
 [ 14  14  12   8  36]]


###Задание 9
создайте матрицу 3 на 5 со случайными целыми числами в диапазоне от -15 до 15
найдите максимум и минимум
найдите среднее по столбцам
найдите среднее по строкам

In [14]:
first = np.random.randint(-15, 15, (3,5))
print(first)

print(f"max:{first.max()}")
print(f"min:{first.min()}")
print(f"average by columns:{np.mean(first, axis = 0)}")
print(f"average by rows:{np.mean(first, axis = 1)}")


[[ 14  11   7  12  12]
 [ -6 -12   1  12   2]
 [-15 -13  -8   6  -2]]
max:14
min:-15
average by columns:[-2.33333333 -4.66666667  0.         10.          4.        ]
average by rows:[11.2 -0.6 -6.4]


###Задание 10
даны две матрицы
убедитесь, что их можно пермножить
произведите операцию умножения матриц, если это возможно, иначе выведите ошибку

In [15]:
a = np.random.randint(-10, 10, (2, 5))
first_axis = np.random.randint(4, 6)
b = np.random.randint(-10, 10, (first_axis, 3))

if a.shape[1] == first_axis:
  print(a @ b)
else:
  print("Размеры матрицы не подходят для умножения")


[[ 12  78 -51]
 [134 -52 -94]]


###Задание 11
создайте матрицу 5 на 5 заполненную равномерным распределением с диапазоно 2-12
заполните все элементы ниже главной диагонали нулями

In [16]:
mask = np.random.uniform(2, 12, (5, 5)) 
matrix = np.triu(mask)

print(matrix)

[[ 5.19573213  7.77799753  5.48439374 10.08238082  6.80708603]
 [ 0.         11.79698838  9.91202838  5.05063999  8.86236686]
 [ 0.          0.         10.56397617  5.65129299  8.95763833]
 [ 0.          0.          0.          9.10263013  2.1380896 ]
 [ 0.          0.          0.          0.          7.29239649]]


###Задание 12
создайте матрицу 5 на 5 заполненную нормальным распределением с парметрами среднее 10 и отклонение 2
заполните все элементы на главной диагонали нулями

In [17]:
matrix = np.random.normal(10, 2, (5,5))

np.fill_diagonal(matrix, 0)

print(matrix)

[[ 0.         12.117185   10.89461228 11.39046669 13.39138555]
 [ 8.41230202  0.         10.97783081 11.30718636  8.3738151 ]
 [12.18044222  7.86198532  0.         12.00858843  6.17534695]
 [ 9.04009563  8.49055196  6.05850519  0.         12.41438183]
 [12.0171472   8.43063377 10.52628102  7.20674722  0.        ]]


###Задание 13
дано два массива, проверить одинаковы ли они

In [18]:
a = np.random.randint(0,2,5)
print(a)
b = np.random.randint(0,2,5)
print(b)
equal = np.array_equal(a, b)
equal

[1 1 0 1 0]
[1 1 0 0 0]


False

###Задание 14
сгенерируйте матрицу случайного размера:
строк от 3 до 7
столбцов от 2 до 12
сгенерируйте число N - размер выборки так, чтобы оно не превышало половину количества элементов сгенерированной матрицы, но было больше 0
сделайте случайную выборку N элементов

In [19]:
r, c = np.random.randint(3, 7), np.random.randint(2, 12)
a = np.random.randint(0, 10, (r, c))
print(a)
N = np.random.randint(0, r * c/2)
print(N)
sample = np.random.choice(a.flatten(), N)
print(sample)

[[9 9 8 3 9]
 [6 0 3 8 6]
 [6 7 4 6 6]
 [0 3 2 5 1]
 [1 5 1 0 7]]
8
[1 8 9 9 8 1 6 1]


###Задание 15
дан вектор, проверить есть в нем Nan
проверить есть в нем знак бесконечности
заполнить их нулями

In [20]:
a = np.array([1, np.NaN, np.Inf], float)

a[np.where((np.isnan(a) == True) | (np.isinf(a) == True))] = 0

a


array([1., 0., 0.])

###Задание 16
сгенерировать массив с произвольным числом осей
определить сколько у него осей

In [21]:
count_axis = np.random.randint(10)

dimension_axes = np.random.randint(0,10,count_axis)

matrix = np.random.randint(0,5,dimension_axes)
print(matrix.shape)


(8, 5, 6, 2, 1)


###Задание 17
сгенерируйте матрицу 10 на 3 с нормальным распределением, среднее 50, отклонение 10
найдите индексы максимальных элементов в каждой строке
найдите сами элементы

In [22]:
matrix = np.random.normal(50, 10, (10,3))
print(matrix)

indexes = np.argmax(matrix, axis = 1)
print(indexes)

print(np.amax(matrix, axis = 1))

[[53.3178996  37.77862215 55.19701309]
 [58.6017231  58.86041972 50.81322686]
 [40.81998171 55.37038963 37.1040903 ]
 [45.37774671 35.83698697 28.32141385]
 [45.29407347 50.56046347 44.52041393]
 [59.25089324 45.38670281 39.91557315]
 [73.73167679 56.42356958 58.06431251]
 [51.65064206 35.12471828 55.78689865]
 [44.04293563 56.09070793 51.9432573 ]
 [55.35188747 42.17912451 49.80481398]]
[2 1 1 0 1 0 0 2 1 0]
[55.19701309 58.86041972 55.37038963 45.37774671 50.56046347 59.25089324
 73.73167679 55.78689865 56.09070793 55.35188747]
