In [3]:
import numpy as np

1. Задание
- проверьте тип объекта python_list
- если это не numpy ndarray, то преобразуйте к нему
- проверьте, что на выходе вы получили объект python_list желаемого типа

In [4]:
python_list = [1, 12, 13, 45, 76, 45, 98, 0]

if (type(python_list) != np.ndarray):
    python_list = np.asarray(python_list)
    
print(type(python_list))

<class 'numpy.ndarray'>


2. Задание
- создайте одномерный массив numpy из 10 элементов заполненный числом 1.5

In [5]:
z = np.full(10, 1.5)
print(z)

[1.5 1.5 1.5 1.5 1.5 1.5 1.5 1.5 1.5 1.5]


3. Задание
- создайте двумерный массив numpy из 25 элементов заполненный числом 0

In [6]:
z = np.full((5, 5), 0)
print(z)

[[0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]]


4. Задание
- создайте одномерный массив numpy из 12 элементов заполненный числом 1

In [7]:
ones = np.full(12, 1)
print(ones)

[1 1 1 1 1 1 1 1 1 1 1 1]


5. Задание
- преобразуйте массив из предыдущего задания к матрице 3 на 4
- выведите размерность полученного массива

In [8]:
ones = np.reshape(ones, (3, 4))
ones.shape
print(ones)

[[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]]


6. Задание
- создайте матрицу 4 на 5 заполненную числами от 1 до 20
- замените элемент в 3-й строке 4-м столбце на -99

In [9]:
Z = np.arange(1, 21).reshape(4,5)
print(Z)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]


7. Задание
- создайте вектор длинной 15 со случайными целыми числами в диапазоне от -10 до 10
- сделайте реверс вектора

In [10]:
first = np.random.randint(-10, 11, 15)
print(first)
second = np.flip(first)
print(second)

[-10  -5   1   2  -5  10   6   9  -9  -3   9   5   5  10  -3]
[ -3  10   5   5   9  -3  -9   9   6  10  -5   2   1  -5 -10]


8. Задание
- создайте матрицу 5 на 5 со случайными целыми числами в диапазоне от -15 до 15
- замените отрицательные элементы на их квадраты

In [11]:
first = np.random.randint(-15, 16, 25).reshape(5, 5)
print(first)
first = np.where(first < 0, first*first, first)
print(first)

[[  5   8 -10  -4   9]
 [ -2 -13  -4  -3  -1]
 [  1  15   6  -4   0]
 [  1 -13 -10 -12   7]
 [ -1  -4 -11  -7  -4]]
[[  5   8 100  16   9]
 [  4 169  16   9   1]
 [  1  15   6  16   0]
 [  1 169 100 144   7]
 [  1  16 121  49  16]]


9. Задание
- создайте матрицу 3 на 5 со случайными целыми числами в диапазоне от -15 до 15
- найдите максимум и минимум
- найдите среднее по столбцам
- найдите среднее по строкам

In [12]:
first = np.random.randint(-15, 16, 15).reshape(3, 5)
print(first)
print(np.amax(first))
print(np.amin(first))
print(np.mean(first, axis = 0))
print(np.mean(first, axis = 1))

[[ -6 -11  11  -7   1]
 [ -6 -11   3   5   1]
 [-13  -7 -13   3   7]]
11
-13
[-8.33333333 -9.66666667  0.33333333  0.33333333  3.        ]
[-2.4 -1.6 -4.6]


10. Задание
- даны две матрицы
- убедитесь, что их можно пермножить
- произведите операцию умножения матриц, если это возможно, иначе выведите ошибку

In [13]:
a = np.random.randint(-10, 10, (2, 5))
first_axis = np.random.randint(4, 6)
b = np.random.randint(-10, 10, (first_axis, 3))
if (a.shape[1] == b.shape[0]):
    print(np.dot(a,b))
else:
    print("Error")
    

[[-56 -10 -61]
 [ 21 -29 -46]]


11. Задание
- создайте матрицу 5 на 5 заполненную равномерным распределением с диапазоно 2-12
- заполните все элементы ниже главной диагонали нулями

In [14]:
matrix = np.random.uniform(2, 13, (5, 5))
N = matrix.shape[0]
matrix[np.tril_indices(N, -1)] = 0

print(matrix)

[[11.45418827  5.32305025  5.03011431  9.88114652  9.00667212]
 [ 0.          4.77644812  4.44133479  2.03225924  9.46775294]
 [ 0.          0.          3.58699264  7.6621683  12.22294255]
 [ 0.          0.          0.         12.28850024  7.89521205]
 [ 0.          0.          0.          0.          6.5070856 ]]


12. Задание
- создайте матрицу 5 на 5 заполненную нормальным распределением с парметрами среднее 10 и отклонение 2
- заполните все элементы на главной диагонали нулями

In [15]:
matrix = np.random.normal(10, 2, (5, 5))
N = matrix.shape[0]
matrix[np.tril_indices(N, -1)] = 0

print(matrix)

[[ 9.42777551  9.25799494 12.4803802   6.46038672  7.63460863]
 [ 0.         11.08605045 13.97227487  9.91195414  7.23886369]
 [ 0.          0.          8.35266406  8.19536116  8.62830427]
 [ 0.          0.          0.         12.83968717  7.70709799]
 [ 0.          0.          0.          0.          9.06958371]]


13. Задание
- дано два массива, проверить одинаковы ли они

In [16]:
a = np.random.randint(0,2,5)
print(a)
b = np.random.randint(0,2,5)
print(b)
equal = np.array_equal(a, b)
print(equal)

[0 1 1 0 0]
[0 1 1 1 1]
False


14. Задание
- сгенерируйте матрицу случайного размера:
 - строк от 3 до 7
 - столбцов от 2 до 12
- сгенерируйте число N - размер выборки так, чтобы оно не превышало половину количества элементов сгенерированной матрицы, но было больше 0
- сделайте случайную выборку N элементов

In [17]:
r, c = np.random.randint(3, 8), np.random.randint(2, 13)
a = np.random.randint(0, 10, (r, c))
print(a)
N = np.random.randint(1, (r * c) / 2 + 1)
print(N)
a = a.flatten()
sample = np.random.choice(a, N)
print(sample)

[[6 7 9 6 1 5 8 6 5 5]
 [6 0 1 0 7 9 7 2 9 2]
 [2 2 6 3 5 8 2 7 3 8]]
13
[1 5 0 7 7 8 2 7 7 8 8 5 2]


15. Задание
- дан вектор, проверить есть в нем Nan
- проверить есть в нем знак бесконечности
- заполнить их нулями

In [18]:
a = np.array([1, np.NaN, np.Inf], float)

if(np.isnan(np.sum(a))):
    a[np.isnan(a)] = 0

if(np.isinf(np.sum(a))):
    a[np.isinf(a)] = 0

print(a)

[1. 0. 0.]


16. Задание
- сгенерировать массив с произвольным числом осей
- определить сколько у него осей

In [22]:
axis = np.random.randint(1, 13)
print(axis)
matrix = np.random.randint(0, 11, (axis,axis))
print(matrix)

5
[[ 8  4  2  9  7]
 [ 4  2  9  7  5]
 [10  0  2  8  1]
 [ 0  4  2  2  1]
 [10  0  3  7  1]]


17. Задание
- сгенерируйте матрицу 10 на 3 с нормальным распределением, среднее 50, отклонение 10
- найдите индексы максимальных элементов в каждой строке
- найдите сами элементы

In [25]:
matrix = np.random.normal(50, 10, (10,3))
print(matrix)
indexes = np.argmax(matrix, axis=1)
print(indexes)
max_elem = np.amax(matrix, axis=1)
print(max_elem)

[[47.48152886 40.25440688 61.81320313]
 [43.95074958 50.26879454 44.48493298]
 [55.76356757 51.71093497 39.82692775]
 [48.7747764  60.58441517 37.70839243]
 [43.47958169 37.29887468 58.91898856]
 [48.9150156  38.96114757 53.98471135]
 [42.14774962 40.00526499 51.42124397]
 [46.88215913 57.1147079  51.68901672]
 [54.75810797 64.67735421 48.41098771]
 [67.20825485 44.73896718 53.96064321]]
[2 1 0 1 2 2 2 1 1 0]
[61.81320313 50.26879454 55.76356757 60.58441517 58.91898856 53.98471135
 51.42124397 57.1147079  64.67735421 67.20825485]
