In [2]:
import numpy as np

1. Задание
- проверьте тип объекта python_list
- если это не numpy ndarray, то преобразуйте к нему
- проверьте, что на выходе вы получили объект python_list желаемого типа

In [4]:
python_list = [1, 12, 13, 45, 76, 45, 98, 0]
print(type(python_list))
python_list = np.array(python_list)
print(type(python_list))

<class 'list'>
<class 'numpy.ndarray'>


2. Задание
- создайте одномерный массив numpy из 10 элементов заполненный числом 1.5

In [5]:
z = np.full(10, 1.5)
print(z)

[1.5 1.5 1.5 1.5 1.5 1.5 1.5 1.5 1.5 1.5]


3. Задание
- создайте двумерный массив numpy из 25 элементов заполненный числом 0

In [7]:
z = np.array([np.full(25, 0), np.full(25, 0)])
print(z)

[[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]]


4. Задание
- создайте одномерный массив numpy из 12 элементов заполненный числом 1

In [8]:
ones = np.full(12, 1)
print(ones)

[1 1 1 1 1 1 1 1 1 1 1 1]


5. Задание
- преобразуйте массив из предыдущего задания к матрице 3 на 4
- выведите размерность полученного массива

In [12]:
ones = ones.reshape(3, 4)
ones.shape

(3, 4)

6. Задание
- создайте матрицу 4 на 5 заполненную числами от 1 до 20
- замените элемент в 3-й строке 4-м столбце на -99

In [25]:
Z = np.arange(1, 21, 1)
Z = Z.reshape(4, 5)
print(Z)
Z[2, 3] = -99
print(Z)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]
[[  1   2   3   4   5]
 [  6   7   8   9  10]
 [ 11  12  13 -99  15]
 [ 16  17  18  19  20]]


7. Задание
- создайте вектор длинной 15 со случайными целыми числами в диапазоне от -10 до 10
- сделайте реверс вектора

In [27]:
first = np.random.randint(-10, 10, 15)
print(first)
second = np.flip(first)
print(second)

[-1 -7  9  0 -5 -1 -2  5  5  5  7  5 -1 -5  0]
[ 0 -5 -1  5  7  5  5  5 -2 -1 -5  0  9 -7 -1]


8. Задание
- создайте матрицу 5 на 5 со случайными целыми числами в диапазоне от -15 до 15
- замените отрицательные элементы на их квадраты

In [36]:
first = np.random.randint(-15, 15, 25).reshape(5,5)
print(first)
first[(first < 0)] **= 2
print(first)

[[-13  11   4  14  -7]
 [ 10  -2  -7  -6  -9]
 [-13   9 -13  10  -1]
 [-13   1 -14   4   6]
 [ -9  12  -5  10   9]]
[[169  11   4  14  49]
 [ 10   4  49  36  81]
 [169   9 169  10   1]
 [169   1 196   4   6]
 [ 81  12  25  10   9]]


9. Задание
- создайте матрицу 3 на 5 со случайными целыми числами в диапазоне от -15 до 15
- найдите максимум и минимум
- найдите среднее по столбцам
- найдите среднее по строкам

In [51]:
first = np.random.randint(-15, 15, 15).reshape(3,5)
print(first)
print(f'Min: {first.min()}\nMax: {first.max()}')
print(np.mean(first, axis=0))
print(np.mean(first, axis=1))

[[-15  13   6   2   8]
 [ -8 -11  10  14   8]
 [-10  10   9  -9   5]]
Min: -15
Max: 14
[-11.           4.           8.33333333   2.33333333   7.        ]
[2.8 2.6 1. ]


10. Задание
- даны две матрицы
- убедитесь, что их можно пермножить
- произведите операцию умножения матриц, если это возможно, иначе выведите ошибку

In [99]:
a = np.random.randint(-10, 10, (2, 5))
first_axis = np.random.randint(4, 6)
b = np.random.randint(-10, 10, (first_axis, 3))
if a.shape[1] == b.shape[0]:
    print(a @ b)
else:
    print('error')

[[ 6  7  5  8  7]
 [-9  8  7 -1  0]]
[[ -29   -9 -129]
 [ 107   45    1]]


11. Задание
- создайте матрицу 5 на 5 заполненную равномерным распределением с диапазоно 2-12
- заполните все элементы ниже главной диагонали нулями

In [82]:
mask = np.random.uniform(2, 12, (5, 5)) 
matrix = mask.copy()
matrix[np.tril_indices(5, -1)] = 0
print(mask, '\n')
print(matrix)

[[ 3.00828027  8.42473133 11.2303342   8.40411288 10.68949298]
 [ 8.82447765  2.1850345  10.20137673  9.20976182  6.48449125]
 [ 4.69673176  6.93988753  8.22078804  3.67669303  4.37777539]
 [ 2.36474433 10.48355972 11.95566016  6.97290254  9.00448146]
 [11.49000788  9.28104625 11.3615282   6.48250861  2.27640372]] 

[[ 3.00828027  8.42473133 11.2303342   8.40411288 10.68949298]
 [ 0.          2.1850345  10.20137673  9.20976182  6.48449125]
 [ 0.          0.          8.22078804  3.67669303  4.37777539]
 [ 0.          0.          0.          6.97290254  9.00448146]
 [ 0.          0.          0.          0.          2.27640372]]


12. Задание
- создайте матрицу 5 на 5 заполненную нормальным распределением с парметрами среднее 10 и отклонение 2
- заполните все элементы на главной диагонали нулями

In [88]:
mask = np.random.normal(10, 2, (5, 5))
matrix = mask.copy()
np.fill_diagonal(matrix, 0)
print(mask, '\n')
print(matrix)

[[12.40520329 11.59559361  9.10919935 12.11904832  6.30119245]
 [10.8290389  10.21610281 12.73190057 10.26367561 12.09021157]
 [ 9.96472179  6.82235949 10.44464128 10.50489513 10.41278722]
 [11.07720861  7.83597241 11.30161393  7.80245433 10.0812214 ]
 [10.37376267  8.89926642  9.36642882  5.6502473   5.18663286]] 

[[ 0.         11.59559361  9.10919935 12.11904832  6.30119245]
 [10.8290389   0.         12.73190057 10.26367561 12.09021157]
 [ 9.96472179  6.82235949  0.         10.50489513 10.41278722]
 [11.07720861  7.83597241 11.30161393  0.         10.0812214 ]
 [10.37376267  8.89926642  9.36642882  5.6502473   0.        ]]


13. Задание
- дано два массива, проверить одинаковы ли они

In [90]:
a = np.random.randint(0,2,5)
print(a)
b = np.random.randint(0,2,5)
print(b)
equal = np.array_equal(a, b)
equal

[1 0 0 1 1]
[1 1 0 1 1]


False

14. Задание
- сгенерируйте матрицу случайного размера:
 - строк от 3 до 7
 - столбцов от 2 до 12
- сгенерируйте число N - размер выборки так, чтобы оно не превышало половину количества элементов сгенерированной матрицы, но было больше 0
- сделайте случайную выборку N элементов

In [8]:
r, c = np.random.randint(3, 7), np.random.randint(2, 12)
a = np.random.randint(-10, 10, (r, c))
print(a)
N = np.random.randint(1, int(r * c / 2))
print(N)
elements = []
for _ in range(N):
    r, c = np.random.randint(0, a.shape[0]), np.random.randint(0, a.shape[1])
    elements.append(a[r, c])
print(elements)

[[  8   9  -9  -7  -7   5  -2 -10 -10   0 -10]
 [ -4 -10   7   1  -4  -6   7  -9   4   5   0]
 [ -8   7  -9  -4  -7   7   6   5  -6  -3 -10]]
7
[-9, -6, 9, -10, -9, 7, -7]


15. Задание
- дан вектор, проверить есть в нем Nan
- проверить есть в нем знак бесконечности
- заполнить их нулями

In [17]:
a = np.array([1, np.NaN, np.Inf], float)

a[np.isnan(a)] = 0
a[np.isinf(a)] = 0
a

array([1., 0., 0.])

16. Задание
- сгенерировать массив с произвольным числом осей
- определить сколько у него осей

In [ ]:
# axis = 
# print(axis)
# matrix = axis.copy()
# print(...)

17. Задание
- сгенерируйте матрицу 10 на 3 с нормальным распределением, среднее 50, отклонение 10
- найдите индексы максимальных элементов в каждой строке
- найдите сами элементы

In [40]:
matrix = np.random.normal(50, 10, (10,3))
print(matrix, '\n')
values = {}
n = 0
for e in matrix:
    max_v = e.max()
    i, j = np.where(matrix == max_v) 
    print(f'{n})   {max_v}: {i[0], j[0]}')
    n += 1
#     values[max_v] = [i[0], j[0]]


[[49.82961755 45.20836236 51.67375568]
 [54.61233339 43.07961718 66.22849788]
 [41.26186524 49.10102987 48.8635253 ]
 [36.54375885 54.68917184 44.34868736]
 [52.38479663 45.95004721 41.84819337]
 [47.93614498 64.16028385 51.86957855]
 [47.43693516 53.31065015 62.36792985]
 [44.78594331 60.64558806 56.18408795]
 [55.68425851 66.13775594 37.26352398]
 [63.28812494 61.02479145 58.37129355]] 

0)   51.6737556832219: (0, 2)
1)   66.22849788177044: (1, 2)
2)   49.10102987109707: (2, 1)
3)   54.68917183933933: (3, 1)
4)   52.38479662520886: (4, 0)
5)   64.16028385429179: (5, 1)
6)   62.367929854731884: (6, 2)
7)   60.645588061702405: (7, 1)
8)   66.13775594417704: (8, 1)
9)   63.288124941322685: (9, 0)
