In [1]:
import numpy as np

1. Задание
- проверьте тип объекта python_list
- если это не numpy ndarray, то преобразуйте к нему
- проверьте, что на выходе вы получили объект python_list желаемого типа

In [2]:
python_list = [1, 12, 13, 45, 76, 45, 98, 0]
print(type(python_list))
python_list = np.array(python_list)
print(type(python_list))

<class 'list'>
<class 'numpy.ndarray'>


2. Задание
- создайте одномерный массив numpy из 10 элементов заполненный числом 1.5

In [5]:
z = np.array([1.5 for i in range(10)])
print(z)

[1.5 1.5 1.5 1.5 1.5 1.5 1.5 1.5 1.5 1.5]


3. Задание
- создайте двумерный массив numpy из 25 элементов заполненный числом 0

In [3]:
z = np.zeros((5, 5))
print(z)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


4. Задание
- создайте одномерный массив numpy из 12 элементов заполненный числом 1

In [7]:
ones = np.array([1 for j in range(12)])
print(ones)

[1 1 1 1 1 1 1 1 1 1 1 1]


5. Задание
- преобразуйте массив из предыдущего задания к матрице 3 на 4
- выведите размерность полученного массива

In [8]:
ones = ones.reshape(3, 4)
ones.shape

(3, 4)

6. Задание
- создайте матрицу 4 на 5 заполненную числами от 1 до 20
- замените элемент в 3-й строке 4-м столбце на -99

In [11]:
Z = np.random.randint(1, 20, 20).reshape(4, 5)
print(Z)
Z[2, 3] = -99
print(Z)

[[17 18 16 19  2]
 [18 17 14 16  5]
 [ 4  6 12 19  9]
 [18  3  4  1  8]]
[[ 17  18  16  19   2]
 [ 18  17  14  16   5]
 [  4   6  12 -99   9]
 [ 18   3   4   1   8]]


7. Задание
- создайте вектор длинной 15 со случайными целыми числами в диапазоне от -10 до 10
- сделайте реверс вектора

In [13]:
first = np.array([np.random.randint(-10, 10) for z in range(15)])
print(first)
second = first[::-1]
print(second)

[ -7  -4  -2  -9  -9  -6   7   6  -6   1 -10   8   1 -10  -3]
[ -3 -10   1   8 -10   1  -6   6   7  -6  -9  -9  -2  -4  -7]


8. Задание
- создайте матрицу 5 на 5 со случайными целыми числами в диапазоне от -15 до 15
- замените отрицательные элементы на их квадраты

In [16]:
first = np.array([np.random.randint(-15, 15) for x in range(25)]).reshape(5, 5)
print(first)
first[first < 0] **= 2
print(first)

[[  6  -1 -10  11  -6]
 [-12   3   9   1  -9]
 [-11   4   1  -4   4]
 [ -1   9  11  -7 -10]
 [ 12  12   7   9   5]]
[[  6   1 100  11  36]
 [144   3   9   1  81]
 [121   4   1  16   4]
 [  1   9  11  49 100]
 [ 12  12   7   9   5]]


9. Задание
- создайте матрицу 3 на 5 со случайными целыми числами в диапазоне от -15 до 15
- найдите максимум и минимум
- найдите среднее по столбцам
- найдите среднее по строкам

In [27]:
first = np.array([np.random.randint(-15, 15, 15)]).reshape(3, 5)
print(first)
print(np.max(first))
print(np.min(first))
print(np.mean(first, axis=0))
print(np.mean(first, axis=1))

[[  7   6   9  13  -6]
 [ -5 -15   9  14  10]
 [-11  -6   2 -14   1]]
14
-15
[-3.         -5.          6.66666667  4.33333333  1.66666667]
[ 5.8  2.6 -5.6]


10. Задание
- даны две матрицы
- убедитесь, что их можно пермножить
- произведите операцию умножения матриц, если это возможно, иначе выведите ошибку

In [41]:
a = np.random.randint(-10, 10, (2, 5))
first_axis = np.random.randint(4, 6)
b = np.random.randint(-10, 10, (first_axis, 3))
if a.shape[1] == b.shape[0]:
    print(a @ b)
else:
    print('Ошибка')

[[-25   1  71]
 [-51  44  75]]


11. Задание
- создайте матрицу 5 на 5 заполненную равномерным распределением с диапазоно 2-12
- заполните все элементы ниже главной диагонали нулями

In [48]:
#mask =
matrix = np.array(np.linspace(2, 12, 25)).reshape(5, 5)
matrix[np.tril_indices(5, -1)] = 0

print(matrix)

[[ 2.          2.41666667  2.83333333  3.25        3.66666667]
 [ 0.          4.5         4.91666667  5.33333333  5.75      ]
 [ 0.          0.          7.          7.41666667  7.83333333]
 [ 0.          0.          0.          9.5         9.91666667]
 [ 0.          0.          0.          0.         12.        ]]


12. Задание
- создайте матрицу 5 на 5 заполненную нормальным распределением с парметрами среднее 10 и отклонение 2
- заполните все элементы на главной диагонали нулями

In [53]:
#mask =
matrix = np.array([np.random.normal(10, 2) for c in range(25)]).reshape(5, 5)
matrix[np.diag_indices(5)] = 0

print(matrix)

[[ 0.          6.32629905  7.58269858 10.19420403 10.05776825]
 [ 8.93394227  0.         12.62405164 13.09684805 10.07054908]
 [ 8.58286701  8.63528701  0.          7.37779475  8.86826475]
 [ 7.37686875  7.86347024 11.37640817  0.          8.93931273]
 [ 6.871157   14.36250541  8.41168836 13.4345607   0.        ]]


13. Задание
- дано два массива, проверить одинаковы ли они

In [71]:
a = np.random.randint(0,2,5)
print(a)
b = np.random.randint(0,2,5)
print(b)
equal = a == b
equal.all()

[1 0 0 1 0]
[1 0 0 0 0]


False

14. Задание
- сгенерируйте матрицу случайного размера:
 - строк от 3 до 7
 - столбцов от 2 до 12
- сгенерируйте число N - размер выборки так, чтобы оно не превышало половину количества элементов сгенерированной матрицы, но было больше 0
- сделайте случайную выборку N элементов

In [76]:
r, c = np.random.randint(3, 7), np.random.randint(2, 12)
a = np.random.randint(-10, 10, (r, c))
print(a)
N = (r * c) // 2
print(N)
sample = np.random.choice(a.ravel(), size=N)
print(sample)

[[ -9  -4   0  -3   5   4  -7  -1  -1]
 [  4  -6  -1   2  -8  -8   5   2  -2]
 [ -7   5   5   8  -4  -8  -5  -6   5]
 [  8   8   5  -6  -2   8  -1   0   1]
 [  2   6  -1   7  -1   4   3 -10  -4]
 [  9  -8  -5 -10   3   4   2   4  -5]]
27
[ -8  -8   4   1  -5   4  -6  -7   2   5  -7  -4  -9  -7   5  -8 -10   5
  -1  -6   4  -7   4   5  -5   2  -4]


15. Задание
- дан вектор, проверить есть в нем Nan
- проверить есть в нем знак бесконечности
- заполнить их нулями

In [77]:
a = np.array([1, np.NaN, np.Inf], float)

print(np.isnan(a))
print(np.isinf(a))


[False  True False]
False
[False False  True]


16. Задание
- сгенерировать массив с произвольным числом осей
- определить сколько у него осей

In [122]:
matrix = np.random.randint(0, 2, ([np.random.randint(1, 5)]*np.random.randint(2, 6)))
print(matrix.shape)
print(matrix)

(4, 4, 4, 4)
[[[[1 0 0 1]
   [0 0 0 0]
   [0 0 0 1]
   [0 0 1 1]]

  [[0 0 0 0]
   [1 1 0 0]
   [0 1 0 1]
   [1 1 0 1]]

  [[0 0 1 0]
   [1 1 0 0]
   [1 1 1 0]
   [0 1 0 1]]

  [[1 0 1 0]
   [1 1 0 0]
   [0 0 1 1]
   [1 1 0 0]]]


 [[[0 0 1 0]
   [1 1 1 0]
   [1 1 0 0]
   [1 1 1 1]]

  [[0 0 0 1]
   [0 0 1 1]
   [1 0 0 1]
   [0 0 0 1]]

  [[0 1 0 1]
   [0 1 1 0]
   [1 1 0 1]
   [0 0 0 1]]

  [[0 1 1 1]
   [1 0 0 1]
   [1 1 1 0]
   [1 1 0 1]]]


 [[[1 1 1 0]
   [1 0 0 1]
   [0 0 1 0]
   [1 0 0 0]]

  [[0 1 0 1]
   [0 0 0 0]
   [1 0 0 0]
   [0 0 0 0]]

  [[0 1 1 0]
   [1 1 1 1]
   [0 1 0 1]
   [0 1 1 0]]

  [[0 1 1 1]
   [1 0 1 1]
   [0 1 0 0]
   [0 1 1 1]]]


 [[[0 0 1 0]
   [1 1 0 0]
   [1 0 1 1]
   [1 1 0 1]]

  [[1 0 1 1]
   [0 1 0 0]
   [0 1 0 0]
   [0 0 1 1]]

  [[0 0 1 1]
   [1 0 0 1]
   [1 1 0 0]
   [0 1 0 0]]

  [[0 0 1 0]
   [1 0 1 1]
   [1 1 1 0]
   [0 0 1 0]]]]


17. Задание
- сгенерируйте матрицу 10 на 3 с нормальным распределением, среднее 50, отклонение 10
- найдите индексы максимальных элементов в каждой строке
- найдите сами элементы

In [79]:
Matrix = np.random.normal(50, 10, (10,3))
print(Matrix)
indexes = np.argmax(Matrix, axis=1)
print(indexes)
print(np.amax(Matrix, axis=1))

[[51.40027567 33.30430468 45.264732  ]
 [62.8625294  45.78707053 42.27779131]
 [40.22214076 47.34649647 60.93443534]
 [20.97587447 54.30548878 38.21993906]
 [52.08064334 46.40567518 35.6579447 ]
 [52.8761884  27.7944046  42.42578905]
 [50.24637064 57.46672647 47.25224784]
 [47.63133328 61.54324542 61.83160697]
 [58.86384325 42.28252043 63.90076771]
 [66.51882066 35.04164702 42.58267977]]
[0 0 2 1 0 0 1 2 2 0]
[51.40027567 62.8625294  60.93443534 54.30548878 52.08064334 52.8761884
 57.46672647 61.83160697 63.90076771 66.51882066]
