In [1]:
import numpy as np

1. Задание
- проверьте тип объекта python_list
- если это не numpy ndarray, то преобразуйте к нему
- проверьте, что на выходе вы получили объект python_list желаемого типа

In [2]:
python_list = [1, 12, 13, 45, 76, 45, 98, 0]
print(type(python_list))
python_list = np.array(python_list)
print(type(python_list))

<class 'list'>
<class 'numpy.ndarray'>


2. Задание
- создайте одномерный массив numpy из 10 элементов заполненный числом 1.5

In [3]:
z = np.full(10, 1.5)
print(z)

[1.5 1.5 1.5 1.5 1.5 1.5 1.5 1.5 1.5 1.5]


3. Задание
- создайте двумерный массив numpy из 25 элементов заполненный числом 0

In [4]:
z = z = np.zeros((5, 5))

print(z)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


4. Задание
- создайте одномерный массив numpy из 12 элементов заполненный числом 1

In [5]:
ones = np.ones(12)
print(ones)

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


5. Задание
- преобразуйте массив из предыдущего задания к матрице 3 на 4
- выведите размерность полученного массива

In [6]:
ones = ones.reshape(3,4)
ones.shape

(3, 4)

6. Задание
- создайте матрицу 4 на 5 заполненную числами от 1 до 20
- замените элемент в 3-й строке 4-м столбце на -99

In [7]:
Z = np.arange(1, 21, 1).reshape(4, 5)
print(Z)
Z[2, 3] = -99
print(Z)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]
[[  1   2   3   4   5]
 [  6   7   8   9  10]
 [ 11  12  13 -99  15]
 [ 16  17  18  19  20]]


7. Задание
- создайте вектор длинной 15 со случайными целыми числами в диапазоне от -10 до 10
- сделайте реверс вектора

In [8]:
first = np.random.randint(-10, 11, 15)
print(first)
second = first[::-1]
print(second)

[ -3 -10 -10  10   2   4  -9  10   4   1  -7   7   3  -5  -3]
[ -3  -5   3   7  -7   1   4  10  -9   4   2  10 -10 -10  -3]


8. Задание
- создайте матрицу 5 на 5 со случайными целыми числами в диапазоне от -15 до 15
- замените отрицательные элементы на их квадраты

In [9]:
first = np.random.randint(-15, 16, 25).reshape(5, 5)
print(first)
first = np.where(first < 0, first**2, first)
print(first)

[[  2  -1 -15 -11   4]
 [ 11  -5  -9   0 -13]
 [ -7   1 -12 -12  -3]
 [  1  -7 -15   2  -9]
 [  0   3 -12   0  13]]
[[  2   1 225 121   4]
 [ 11  25  81   0 169]
 [ 49   1 144 144   9]
 [  1  49 225   2  81]
 [  0   3 144   0  13]]


9. Задание
- создайте матрицу 3 на 5 со случайными целыми числами в диапазоне от -15 до 15
- найдите максимум и минимум
- найдите среднее по столбцам
- найдите среднее по строкам

In [10]:
first = np.random.randint(-15, 16, 15).reshape(3, 5)
print(first)
first.max(), first.min(), first.mean(axis=0), first.mean(axis=1)

[[ 12   5  -3  11   6]
 [  4  -5  -3   0  14]
 [ 15  -1 -10  -9   3]]


(15,
 -10,
 array([10.33333333, -0.33333333, -5.33333333,  0.66666667,  7.66666667]),
 array([ 6.2,  2. , -0.4]))

10. Задание
- даны две матрицы
- убедитесь, что их можно пермножить
- произведите операцию умножения матриц, если это возможно, иначе выведите ошибку

In [11]:
a = np.random.randint(-10, 10, (2, 5))
first_axis = np.random.randint(4, 6)
b = np.random.randint(-10, 10, (first_axis, 3))
if a.shape[1] == b.shape[0]:
    print(a @ b)
else:
    print('err')

[[  36  -54   96]
 [ -47 -137   79]]


11. Задание
- создайте матрицу 5 на 5 заполненную равномерным распределением с диапазоно 2-12
- заполните все элементы ниже главной диагонали нулями

In [12]:
mask = np.random.uniform(2, -12, (5, 5)) 
matrix = np.copy(mask)
for i in range(5):
  for j in range(5):
    if j < i:
      matrix[i, j] = 0

print(matrix)

[[ -2.61775722  -1.67086735  -2.27801851  -6.93616721  -7.45792731]
 [  0.          -6.15690924   0.62688566   0.60474397  -7.53560122]
 [  0.           0.         -11.70636778  -3.90126739  -1.98764308]
 [  0.           0.           0.          -9.70455908 -10.8963226 ]
 [  0.           0.           0.           0.          -2.1782692 ]]


12. Задание
- создайте матрицу 5 на 5 заполненную нормальным распределением с парметрами среднее 10 и отклонение 2
- заполните все элементы на главной диагонали нулями

In [13]:
mask = np.random.normal(10, 2, 25).reshape(5, 5)
matrix = np.copy(mask)

for i in range(5):
  for j in range(5):
    if j == i:
      matrix[i, j] = 0

print(matrix)

[[ 0.         10.18238614 11.91385332  8.31314191  7.16254416]
 [ 9.49416669  0.          8.87762329 11.12641883 10.55408449]
 [ 6.60673358  6.12302958  0.         11.78786698 11.4615063 ]
 [10.08653577 10.05468692 10.00824118  0.         12.99399982]
 [12.01515492  7.92418921  9.0942127   9.01347768  0.        ]]


13. Задание
- дано два массива, проверить одинаковы ли они

In [14]:
a = np.random.randint(0,2,5)
print(a)
b = np.random.randint(0,2,5)
print(b)
equal = sum(a == b) == len(a)
equal

[1 0 0 0 0]
[1 1 0 1 0]


False

14. Задание
- сгенерируйте матрицу случайного размера:
 - строк от 3 до 7
 - столбцов от 2 до 12
- сгенерируйте число N - размер выборки так, чтобы оно не превышало половину количества элементов сгенерированной матрицы, но было больше 0
- сделайте случайную выборку N элементов

In [15]:
import random
import math

r, c = random.randint(3, 7), random.randint(2, 12)
a = np.random.randint(0, 100, r * c).reshape(r, c)
print(a)
N = random.randint(1, math.floor(r * c / 2))
print(N)
sample = np.random.choice(a.flatten(), N)
print(sample)

[[61  2 49 59  9 31 40 42 45  4 70]
 [11 22 73 31 14 48 51 26 96 69 69]
 [18 80 30 20 67 73 68 82 12 83 21]
 [ 7 42 72 85 57 36 66 63 74 37 18]
 [ 2 87 58 27 79 71 24 67 80 18 29]]
20
[67 70 42 37 69 24 72 18 48 57 31 21 85 69  2 67 74 79 40 96]


15. Задание
- дан вектор, проверить есть в нем Nan
- проверить есть в нем знак бесконечности
- заполнить их нулями

In [16]:
a = np.array([1, np.NaN,  np.Inf], float)
for i, e in enumerate(a):
  if np.isnan(e) or np.isinf(e):
    a[i] = 0
a

array([1., 0., 0.])

16. Задание
- сгенерировать массив с произвольным числом осей
- определить сколько у него осей

In [17]:
axis = random.randint(1, 32)
print(axis)
matrix = np.zeros(tuple(np.ones((axis), dtype=int)))
print(len(matrix.shape))

24
24


17. Задание
- сгенерируйте матрицу 10 на 3 с нормальным распределением, среднее 50, отклонение 10
- найдите индексы максимальных элементов в каждой строке
- найдите сами элементы

In [18]:
matrix = np.random.normal(50, 10, (10,3))
print(matrix)
indexes = ([list(item).index(min(item)) for item in matrix])
print(indexes)
print(matrix.min(axis=1))

[[37.40050676 50.32378478 27.00206948]
 [53.26304936 49.19480125 50.78815875]
 [56.14512038 62.83737387 37.25231629]
 [66.89832777 49.51868862 60.56248615]
 [46.90543492 43.61393481 57.70402322]
 [56.99272333 73.20515882 45.65732603]
 [41.55582669 52.51231989 32.21895004]
 [48.05808254 50.78640518 37.77281941]
 [57.72747562 66.61338244 37.49564976]
 [67.92895952 38.51751088 65.11972469]]
[2, 1, 2, 1, 1, 2, 2, 2, 2, 1]
[27.00206948 49.19480125 37.25231629 49.51868862 43.61393481 45.65732603
 32.21895004 37.77281941 37.49564976 38.51751088]
