In [3]:
import numpy as np

1. Задание
- проверьте тип объекта python_list
- если это не numpy ndarray, то преобразуйте к нему
- проверьте, что на выходе вы получили объект python_list желаемого типа

In [6]:
python_list = [1, 12, 13, 45, 76, 45, 98, 0]
print(type(python_list))
python_list = np.array(python_list)
print(type(python_list))

<class 'list'>
<class 'numpy.ndarray'>


2. Задание
- создайте одномерный массив numpy из 10 элементов заполненный числом 1.5

In [9]:
z = np.array([1.5 for i in range(10)])
print(z)

[1.5 1.5 1.5 1.5 1.5 1.5 1.5 1.5 1.5 1.5]


3. Задание
- создайте двумерный массив numpy из 25 элементов заполненный числом 0

In [10]:
z = np.zeros((5,5))
print(z)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


4. Задание
- создайте одномерный массив numpy из 12 элементов заполненный числом 1

In [ ]:
ones = np.array([1 for i in range (12)])
print(ones)

5. Задание
- преобразуйте массив из предыдущего задания к матрице 3 на 4
- выведите размерность полученного массива

In [12]:
ones = np.array([1 for i in range (12)]).reshape(3, 4)
ones.shape

(3, 4)

6. Задание
- создайте матрицу 4 на 5 заполненную числами от 1 до 20
- замените элемент в 3-й строке 4-м столбце на -99

In [14]:
Z = np.array([i for i in range(1, 21)]).reshape(4, 5)
print(Z)
Z[3, 4] = -99
print(Z)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]
[[  1   2   3   4   5]
 [  6   7   8   9  10]
 [ 11  12  13  14  15]
 [ 16  17  18  19 -99]]


7. Задание
- создайте вектор длинной 15 со случайными целыми числами в диапазоне от -10 до 10
- сделайте реверс вектора

In [17]:
first = np.random.randint(-10, 10, (15))
print(first)
second = reversed(first)
print(second)

[ -9 -10   8   6  -3  -6   1  -4  -9   4  -9   1   5   3   3]


8. Задание
- создайте матрицу 5 на 5 со случайными целыми числами в диапазоне от -15 до 15
- замените отрицательные элементы на их квадраты

In [24]:
first = np.random.randint(-15, 15, (5, 5))
print(first)

print(
    np
    .array([item*item if item < 0 else item for item in first.flatten()])
    .reshape(5,5))

[[  9 -10  -2 -15  -4]
 [-13 -15 -10 -15  -9]
 [  6  -9  -4  13 -12]
 [-12  -1  -5  -1  14]
 [ -2  -9   2  -9  10]]
[[  9 100   4 225  16]
 [169 225 100 225  81]
 [  6  81  16  13 144]
 [144   1  25   1  14]
 [  4  81   2  81  10]]


9. Задание
- создайте матрицу 3 на 5 со случайными целыми числами в диапазоне от -15 до 15
- найдите максимум и минимум
- найдите среднее по столбцам
- найдите среднее по строкам

In [29]:
first = np.random.randint(-15, 15, (3, 5))
print(first)
print(first.max())
print(np.mean(first, axis=0))
print(np.mean(first, axis=1))

[[  8  -8   7  -9  12]
 [ -5 -13   4  -6  -5]
 [  6  -3 -13  13 -11]]
13
[ 3.         -8.         -0.66666667 -0.66666667 -1.33333333]
[ 2.  -5.  -1.6]


10. Задание
- даны две матрицы
- убедитесь, что их можно пермножить
- произведите операцию умножения матриц, если это возможно, иначе выведите ошибку

In [32]:
a = np.random.randint(-10, 10, (2, 5))
first_axis = np.random.randint(4, 6)
b = np.random.randint(-10, 10, (first_axis, 3))
print(a,'\n', b)
if a.shape[1] == b.shape[0]:
    print(a @ b)
else:
    print('err')

[[ -3   9  -7  -4 -10]
 [ -9   4  -4  -9  -8]] 
 [[-5 -5 -5]
 [ 1 -2  1]
 [ 5 -1 -6]
 [ 6 -9  5]]
err


11. Задание
- создайте матрицу 5 на 5 заполненную равномерным распределением с диапазоно 2-12
- заполните все элементы ниже главной диагонали нулями

In [47]:
mask = np.fromfunction(lambda x, y: x <= y, (5, 5)).astype(int)
matrix = np.random.uniform(2, 12, (5, 5)) 
print(mask)
print()
print(matrix)
print()
print(mask * matrix)

[[1 1 1 1 1]
 [0 1 1 1 1]
 [0 0 1 1 1]
 [0 0 0 1 1]
 [0 0 0 0 1]]

[[10.91848798  6.92659776  3.61044972  3.76123761  2.75709681]
 [ 9.48006875  4.78720695 11.53040831  9.77860092  2.94363025]
 [ 6.8160005   7.82262577 11.02010864  5.3753274   2.28835358]
 [ 7.16976799 11.84423373  6.03042303  9.94426089 11.44563102]
 [ 5.98797597  2.38694542  8.5701645   3.77496431  3.24636326]]

[[10.91848798  6.92659776  3.61044972  3.76123761  2.75709681]
 [ 0.          4.78720695 11.53040831  9.77860092  2.94363025]
 [ 0.          0.         11.02010864  5.3753274   2.28835358]
 [ 0.          0.          0.          9.94426089 11.44563102]
 [ 0.          0.          0.          0.          3.24636326]]


12. Задание
- создайте матрицу 5 на 5 заполненную нормальным распределением с парметрами среднее 10 и отклонение 2
- заполните все элементы на главной диагонали нулями

In [52]:
mask = np.fromfunction(lambda x, y: x != y, (5, 5)).astype(int)
matrix =  np.random.normal(10, 2, (5, 5))

print(mask)

print(matrix*mask)

[[0 1 1 1 1]
 [1 0 1 1 1]
 [1 1 0 1 1]
 [1 1 1 0 1]
 [1 1 1 1 0]]
[[ 0.         12.32037979  9.33107956 10.65737947 12.70701444]
 [10.71743075  0.         11.49156814 11.42766561  7.35856052]
 [ 9.33276368  7.89385361  0.          6.9127609   8.79411146]
 [ 8.88900445  9.86891529 10.48804995  0.         11.10189233]
 [11.85526742 10.88986187 13.31722151  6.8573967   0.        ]]


13. Задание
- дано два массива, проверить одинаковы ли они

In [54]:
a = np.random.randint(0,2,5)
print(a)
b = np.random.randint(0,2,5)
print(b)
equal = all(a == b)
equal

[0 1 1 0 0]
[0 0 0 1 1]


False

14. Задание
- сгенерируйте матрицу случайного размера:
 - строк от 3 до 7
 - столбцов от 2 до 12
- сгенерируйте число N - размер выборки так, чтобы оно не превышало половину количества элементов сгенерированной матрицы, но было больше 0
- сделайте случайную выборку N элементов

In [63]:
r, c = np.random.randint(3, 7), np.random.randint(2, 12)
print(r,c)
a = np.random.randint(0, 100, size=(r, c))
print(a)
N = np.random.randint(1, r * c / 2)
print(N)
sample = np.random.choice(a.flatten(), N)
print(sample)

3 8
[[93 72 23  1 64 55 25 34]
 [59 22 12 20 86 29 49 72]
 [85 89 28 65 41 11 36 93]]
5
[93 25 55 85 22]


15. Задание
- дан вектор, проверить есть в нем Nan
- проверить есть в нем знак бесконечности
- заполнить их нулями

In [87]:
a = np.array([1, np.NaN, np.Inf], float)
print(any(np.isnan(a)))
print(any(np.isinf(a)))
np.select([~np.isnan(a) & ~np.isinf(a)], [a], 0)

True
True


array([1., 0., 0.])

16. Задание
- сгенерировать массив с произвольным числом осей
- определить сколько у него осей

In [97]:
axis = np.random.randint(1, 32)
print(axis)
matrix = np.zeros([1 for i in range(axis)])
print(matrix.ndim)

23
23


17. Задание
- сгенерируйте матрицу 10 на 3 с нормальным распределением, среднее 50, отклонение 10
- найдите индексы максимальных элементов в каждой строке
- найдите сами элементы

In [103]:
matrix = np.random.normal(50, 10, (10,3))
print(matrix)
indexes = ([list(line).index(max(line)) for line in matrix])
print(indexes)
print([line[indexes[i]] for i, line in enumerate(matrix)])

[[46.66247631 64.90999751 35.20936111]
 [36.73801987 35.49818233 51.16047761]
 [43.70226384 49.25069999 54.0762742 ]
 [54.3823302  50.12262375 49.84751966]
 [58.73230389 45.44749236 39.16232101]
 [43.42648427 50.97592469 54.52013615]
 [61.08080432 47.42343666 49.54119507]
 [59.10017121 44.99528693 58.36038814]
 [51.20333563 47.69247928 49.05142261]
 [54.15399904 39.84489525 54.49399119]]
[1, 2, 2, 0, 0, 2, 0, 0, 0, 2]
[64.90999750766508, 51.1604776137763, 54.07627420066281, 54.38233020183029, 58.73230389409902, 54.52013615293884, 61.08080432412204, 59.100171208616324, 51.20333563247498, 54.49399119165947]
