# Numpy
https://habr.com/ru/post/352678/
https://pythonworld.ru/numpy

In [1]:
import numpy as np

### Введение

In [ ]:
L = range(10000)
%timeit [i**2 for i in L]

The slowest run took 5.84 times longer than the fastest. This could mean that an intermediate result is being cached.
100 loops, best of 5: 2.81 ms per loop


In [ ]:
a = np.arange(10000)
%timeit a**2

The slowest run took 647.47 times longer than the fastest. This could mean that an intermediate result is being cached.
100000 loops, best of 5: 6.6 µs per loop


In [ ]:
?np.array

Поиск в документации

In [ ]:
np.lookfor("stack")

Search results for 'stack'
--------------------------
numpy.dstack
    Stack arrays in sequence depth wise (along third axis).
numpy.hstack
    Stack arrays in sequence horizontally (column wise).
numpy.row_stack
    Stack arrays in sequence vertically (row wise).
numpy.column_stack
    Stack 1-D arrays as columns into a 2-D array.
numpy.ma.stack
    Join a sequence of arrays along a new axis.
numpy.ma.dstack
    Stack arrays in sequence depth wise (along third axis).
numpy.ma.hstack
    Stack arrays in sequence horizontally (column wise).
numpy.ma.row_stack
    Stack arrays in sequence vertically (row wise).
numpy.ma.column_stack
    Stack 1-D arrays as columns into a 2-D array.
numpy.stack
    Join a sequence of arrays along a new axis.
numpy.distutils.misc_util.get_frame
    Return frame object from call stack with given level.
numpy.cov
    Estimate a covariance matrix, given data and weights.
numpy.block
    Assemble an nd-array from nested lists of blocks.
numpy.split
    Split a

### Генерация данных

In [ ]:
# создание вектора из существующего листа с указанием типа чисел
np.array([1, 2, 3], 'float')

array([1., 2., 3.])

In [ ]:
# создание матрицы из существующего списка
type(np.array([[1, 2, 3], [4, 5, 6]]))

numpy.ndarray

In [ ]:
np.array([[1, 2, 3], [4, 5, 6]])

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
# генерация нулевой матрицы
np.zeros((3, 5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [3]:
# генерация единичной матрицы заданной размерности
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [ ]:
# создание диагональной матрицы, по заданной диагонали
np.diag(np.array([1, 2, 3, 4]))

array([[1, 0, 0, 0],
       [0, 2, 0, 0],
       [0, 0, 3, 0],
       [0, 0, 0, 4]])

In [ ]:
# генерация случайных чисел основанная на случайных данных заполняющих оперативную память в данный момент
np.empty(10)

array([0.0000e+000, 1.5563e-321, 0.0000e+000,         nan, 0.0000e+000,
       8.9021e-320, 0.0000e+000,         nan, 0.0000e+000, 6.0054e-320])

In [ ]:
# генерация чисел в диапазоне с заданным шагом
np.arange(10, 31, 5) # начало, конец (не включается), шаг

array([10, 15, 20, 25, 30])

In [ ]:
# генерация заданного количества чисел равномерно заполняющих диапазон
np.linspace(0, 2, 9) # начало, конец (включается), количество чисел в массиве

array([0.  , 0.25, 0.5 , 0.75, 1.  , 1.25, 1.5 , 1.75, 2.  ])

In [ ]:
# генерация чисел по правилу основаному на зависимоти от номеров строк и столбцов
np.fromfunction(lambda x, y: x * y, (3, 4))

array([[0., 0., 0., 0.],
       [0., 1., 2., 3.],
       [0., 2., 4., 6.]])

In [ ]:
# генерация случайных целых чисел из диапазона 0-1, 1  не включено
np.random.sample((3,4))

array([[0.96660969, 0.9570126 , 0.59797368, 0.73130075],
       [0.34038522, 0.0920556 , 0.46349802, 0.50869889],
       [0.08846017, 0.52803522, 0.99215804, 0.39503593]])

In [ ]:
# генерация случайных целых чисел из диапазона 0-1, 1  не включено
np.random.sample(5)

array([0.50755507, 0.0211933 , 0.43352176, 0.44631306, 0.23881999])

In [ ]:
# генерация случайных целых чисел
np.random.randint(0, 5, 10) # с какого числа, по какое число (не включительно), сколько чисел генерировать

array([0, 4, 0, 1, 3, 1, 0, 0, 4, 4])

In [ ]:
# генерация случайных целых чисел
np.random.randint(0, 10, 25).reshape(5,5)

array([[6, 6, 2, 4, 1],
       [5, 5, 5, 5, 8],
       [6, 7, 2, 3, 9],
       [7, 2, 1, 1, 9],
       [6, 5, 9, 2, 1]])

In [ ]:
# генерация случайных целых чисел
np.random.randint(0, 3, (2, 10))

array([[2, 2, 1, 0, 2, 1, 2, 0, 0, 1],
       [1, 1, 2, 2, 1, 1, 0, 1, 2, 1]])

In [ ]:
# генерация чисел согласно равномерному распределению
np.random.uniform(2, 8, (2, 10)) 

array([[6.4494745 , 3.62772333, 2.70541155, 5.28776014, 4.74833514,
        6.56511238, 3.72307085, 6.75398835, 5.10404535, 2.16721212],
       [4.40575796, 7.74310877, 7.87199027, 2.79956879, 4.86845039,
        6.70225239, 5.57999937, 6.34579795, 3.74721352, 6.59826746]])

In [ ]:
# генерация чисел согласно распределению пуассона
np.random.poisson(10, 5)  # 5 numbers, lambda=2.5

array([10,  9, 12, 10,  8])

In [ ]:
# генерация чисел согласно биномиальному распределению
np.random.binomial(4, 0.3, 5)  # 5 numbers, n=4, p=0.3

array([2, 1, 1, 0, 2])

In [ ]:
# нормальное распределение
f = np.random.normal(10, 2, 100000)
f.mean(), f.std()

(10.001507893220248, 2.001266783294607)

In [ ]:
np.random.seed(420)
np.random.random(10)

array([0.31564591, 0.45303068, 0.26698226, 0.10892818, 0.86816648,
       0.62972852, 0.35251871, 0.0675376 , 0.62635059, 0.59866086])

In [ ]:
np.random.seed(1000)
np.random.random(10)

array([0.65358959, 0.11500694, 0.95028286, 0.4821914 , 0.87247454,
       0.21233268, 0.04070962, 0.39719446, 0.2331322 , 0.84174072])

### Базовые операции

In [ ]:
# массивы одного размера
import numpy as np
a = np.array([20, 30, 40, 50])
b = np.arange(4)
print(
'массив b:',
b,
'a + b:',
a + b,
'a - b:',
a - b,
'a * b:',
a * b,
'a / b:',
a / b,
'a ** b:',
a ** b,
'a % b:',
a % b,
'a // b:',
a // b,
sep = '\n') 

массив b:
[0 1 2 3]
a + b:
[20 31 42 53]
a - b:
[20 29 38 47]
a * b:
[  0  30  80 150]
a / b:
[        inf 30.         20.         16.66666667]
a ** b:
[     1     30   1600 125000]
a % b:
[0 0 0 2]
a // b:
[ 0 30 20 16]


In [ ]:
np.nan

nan

In [ ]:
np.inf

inf

In [ ]:
# массивы разной размерности
c = np.array([[1, 2, 3], [4, 5, 6]])
print(c.shape)
d = np.array([[1, 2], [3, 4], [5, 6]])
print(d.shape)
c + d

(2, 3)
(3, 2)


ValueError: ignored

In [ ]:
# но
c = np.array([[1, 2, 3], [4, 5, 6]])
d = np.array([10, 20, 30])
c + d

array([[11, 22, 33],
       [14, 25, 36]])

In [ ]:
# и
c = np.array([[1, 2, 3], [4, 5, 6]])
d = np.array([10, 20]).reshape(-1,1)
c + d

array([[11, 12, 13],
       [24, 25, 26]])

In [ ]:
a = np.array([[1, 2, 3], [4, 5, 6]])
np.sum(a), a.sum(), a.min(), a.max()

(21, 21, 1, 6)

In [ ]:
a.min(axis=0)  # Наименьшее число в каждом столбце

array([1, 2, 3])

In [ ]:
a.min(axis=1) # Наименьшее число в каждой строке

array([1, 4])

### Индексы и срезы

In [ ]:
a = np.arange(10) ** 3
a

array([  0,   1,   8,  27,  64, 125, 216, 343, 512, 729])

In [ ]:
a[2] # выбираем один элемент по индексу

8

In [ ]:
a[[1, 8, 3]]  # выбираем несколько элементов по индексам

array([  1, 512,  27])

In [ ]:
a[3:7]  # выбираем несколько элементов по диапазону индексов

array([ 27,  64, 125, 216])

In [ ]:
a[3:7] = 8 # меняем несколько элементов по диапазону индексов
a

array([  0,   1,   8,   8,   8,   8,   8, 343, 512, 729])

In [ ]:
a[::-1] # реверс массива

array([729, 512, 343,   8,   8,   8,   8,   8,   1,   0])

In [ ]:
b = np.array([[  0, 1, 2, 3],
              [10, 11, 12, 13],
              [20, 21, 22, 23],
              [30, 31, 32, 33],
              [40, 41, 42, 43]])

In [ ]:
 b[2,3]  # Вторая строка, третий столбец

23

In [ ]:
b[2][3]  # Можно и так

23

In [ ]:
b[:,2]  # Второй столбец

array([ 2, 12, 22, 32, 42])

In [ ]:
 b[:2]  # Первые две строки

array([[ 0,  1,  2,  3],
       [10, 11, 12, 13]])

In [ ]:
for row in b:
  print(row)

[0 1 2 3]
[10 11 12 13]
[20 21 22 23]
[30 31 32 33]
[40 41 42 43]


In [ ]:
b[1:3, 2: ]  # Вторая и третья строки и со второго столбца до конца

array([[12, 13],
       [22, 23]])

In [ ]:
b[-1]  # Последняя строка. Эквивалентно b[-1,:]

array([40, 41, 42, 43])

In [ ]:
a = np.array(([[0, 1, 2], [10, 12, 13]], [[100, 101, 102], [110, 112, 113]]))
a.shape # размерность массива

(2, 2, 3)

In [ ]:
a.ndim

3

### Операции с формой массива

In [ ]:
c = a.reshape(6,2) # смена размерности массива
c

array([[  0,   1],
       [  2,  10],
       [ 12,  13],
       [100, 101],
       [102, 110],
       [112, 113]])

In [ ]:
# итерирование идет по строкам
for r in c:
  print(r)

[0 1]
[ 2 10]
[12 13]
[100 101]
[102 110]
[112 113]


In [ ]:
for e in c.flatten(): print(e, end=' ')

0 1 2 10 12 13 100 101 102 110 112 113 

In [ ]:
a.ravel()  # Делает массив плоским

array([  0,   1,   2,  10,  12,  13, 100, 101, 102, 110, 112, 113])

In [ ]:
 c.flatten() # Делает массив плоским

array([  0,   1,   2,  10,  12,  13, 100, 101, 102, 110, 112, 113])

In [ ]:
c

array([[  0,   1],
       [  2,  10],
       [ 12,  13],
       [100, 101],
       [102, 110],
       [112, 113]])

In [ ]:
c.reshape(2,6)

array([[  0,   1,   2,  10,  12,  13],
       [100, 101, 102, 110, 112, 113]])

In [ ]:
c.transpose()  # Транспонирование

array([[  0,   2,  12, 100, 102, 112],
       [  1,  10,  13, 101, 110, 113]])

In [ ]:
 c = c.reshape((2, 6))
 c

array([[  0,   1,   2,  10,  12,  13],
       [100, 101, 102, 110, 112, 113]])

In [ ]:
 a.resize((2, 6))
 a.shape

(2, 6)

In [ ]:
a.reshape((4, -1)) # кол-во столбцов подстроится автоматически под кол-во строк в зависимости от размера массива

array([[  0,   1,   2],
       [ 10,  12,  13],
       [100, 101, 102],
       [110, 112, 113]])

### Объединение массивов

In [ ]:
a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6], [7, 8]])
np.vstack((a, b))

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [ ]:
np.hstack((a, b))

array([[1, 2, 5, 6, 5, 6],
       [3, 4, 7, 8, 7, 8]])

### Копии и представления

In [ ]:
a = np.arange(12)
b = a  # Нового объекта создано не было
print(b is a)  # a и b это два имени для одного и того же объекта ndarray
b.shape = (3,4)  # изменит форму a
a.shape

True


(3, 4)

In [ ]:
c = a.view()
print(c is a) 
print(c.base is a )  # c это представление данных, принадлежащих a

False
True


In [ ]:
c.shape = (2,6)  # форма а не поменяется
a.shape

(3, 4)

In [ ]:
c[0,4] = 1234  # данные а изменятся
a

array([[   0,    1,    2,    3],
       [1234,    5,    6,    7],
       [   8,    9,   10,   11]])

In [ ]:
# Срез массива это представление
s = a[:,1:3]
s[:] = 10
a

array([[   0,   10,   10,    3],
       [1234,   10,   10,    7],
       [   8,   10,   10,   11]])

In [ ]:
 d = a.copy()  # создается новый объект массива с новыми данными
 print(d is a)
 print(d.base is a)  # d не имеет ничего общего с а
 d[0, 0] = 9999
 a

False
False


array([[   0,    1,    2,    3],
       [1234,    5,    6,    7],
       [   8,    9,   10,   11]])

### Разное

In [ ]:
a = np.random.randint(-10, 10, 20).reshape(4,5)
a

array([[  0,  -1,  -6,   8,  -1],
       [  8,   3,   8,   0,   4],
       [ -5,   2,   1,   1, -10],
       [  8,  -6,  -3,   6,   1]])

In [ ]:
np.where(a > 0)

(array([0, 0, 1, 1, 1, 2, 3, 3, 3]), array([1, 2, 0, 3, 4, 4, 0, 2, 4]))

In [ ]:
a[np.where(a < 0)]

array([ -1,  -6,  -1,  -5, -10,  -6,  -3])

In [ ]:
a<0

array([[False,  True,  True, False,  True],
       [False, False, False, False, False],
       [ True, False, False, False,  True],
       [False,  True,  True, False, False]])

In [ ]:
a[a<0]

array([ -1,  -6,  -1,  -5, -10,  -6,  -3])

In [ ]:
a = np.array([1, np.NaN, np.Inf], float)

In [ ]:
 np.isnan(a)

array([False,  True, False])

In [ ]:
np.isinf(a)

array([False, False,  True])

In [ ]:
a = np.random.randint(-10, 10, 20).reshape(4,5)
b = np.random.randint(-10, 10, 40).reshape(5,8)

In [ ]:
np.dot(a,b)

array([[ 131,  -85,  -38,  113,  -43,  -95,  -34,  -38],
       [  36,   43,  -68, -130,   42,   46,  -23,   89],
       [ -33,   22,   69,   -4,   19,   13,   46,  -43],
       [  31,    5,  -65,  157,   47,  -98,  -90,  -25]])

In [ ]:
a @ b

array([[ 131,  -85,  -38,  113,  -43,  -95,  -34,  -38],
       [  36,   43,  -68, -130,   42,   46,  -23,   89],
       [ -33,   22,   69,   -4,   19,   13,   46,  -43],
       [  31,    5,  -65,  157,   47,  -98,  -90,  -25]])

In [ ]:
b @ a

ValueError: ignored

In [ ]:
a.diagonal()

array([ 7,  4,  2, -1])

In [ ]:
np.argmin(a, 0)

array([0, 0, 3, 2, 2])

In [ ]:
a.argmax(1)

array([2, 0, 2, 1])