In [3]:
import numpy as np

1. Задание
- проверьте тип объекта python_list
- если это не numpy ndarray, то преобразуйте к нему
- проверьте, что на выходе вы получили объект python_list желаемого типа

In [9]:
python_list = [1, 12, 13, 45, 76, 45, 98, 0]
print(type(python_list))
#видим, что python_list является структурой list. Преобразуем к ndarray
python_list = np.array(python_list, int)
#проверим успешность проебразования к типу ndarray
print(type(python_list))

<class 'list'>
<class 'numpy.ndarray'>


2. Задание
- создайте одномерный массив numpy из 10 элементов заполненный числом 1.5

In [24]:
z = np.linspace(1.5, 1.5, 10, dtype = float)
print(z)

[1.5 1.5 1.5 1.5 1.5 1.5 1.5 1.5 1.5 1.5]


3. Задание
- создайте двумерный массив numpy из 25 элементов заполненный числом 0

In [26]:
z = np.zeros((5,5))
print(z)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


4. Задание
- создайте одномерный массив numpy из 12 элементов заполненный числом 1

In [38]:
ones = np.ones(12, dtype=int)
print(ones)

[1 1 1 1 1 1 1 1 1 1 1 1]


5. Задание
- преобразуйте массив из предыдущего задания к матрице 3 на 4
- выведите размерность полученного массива

In [30]:
ones = ones.reshape(3,4)
print(ones)
ones.shape

[[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]]


(3, 4)

6. Задание
- создайте матрицу 4 на 5 заполненную числами от 1 до 20
- замените элемент в 3-й строке 4-м столбце на -99

In [45]:
Z = np.arange(20).reshape(4,5)
print(Z)
Z[2][3] = (-99)
print(Z)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]
[[  0   1   2   3   4]
 [  5   6   7   8   9]
 [ 10  11  12 -99  14]
 [ 15  16  17  18  19]]


7. Задание
- создайте вектор длинной 15 со случайными целыми числами в диапазоне от -10 до 10
- сделайте реверс вектора

In [48]:
first = np.random.randint(-10,10,15)
print(first)
second = first[::-1]
print(second)

[ -8   5  -4   7   4   0 -10  -5   3  -9   1  -3  -4  -1   4]
[  4  -1  -4  -3   1  -9   3  -5 -10   0   4   7  -4   5  -8]


8. Задание
- создайте матрицу 5 на 5 со случайными целыми числами в диапазоне от -15 до 15
- замените отрицательные элементы на их квадраты

In [61]:
first = np.random.randint(-15,15,(5,5))
print(first)
for i in range(5):
    for j in range(5):
        if first[i][j] < 0:
            first[i][j] = first[i][j] * first[i][j]
print(first)

[[  6  10   2 -10   5]
 [ -5  -9   1   4   1]
 [  6  -9  -5  -1  -7]
 [  4   7  -1   2  -7]
 [  4   9   5 -14  13]]
[[  6  10   2 100   5]
 [ 25  81   1   4   1]
 [  6  81  25   1  49]
 [  4   7   1   2  49]
 [  4   9   5 196  13]]


9. Задание
- создайте матрицу 3 на 5 со случайными целыми числами в диапазоне от -15 до 15
- найдите максимум и минимум
- найдите среднее по столбцам
- найдите среднее по строкам

In [68]:
first = np.random.randint(-15,15,(3,5))
print(first)
print('max:', first.max(), 'min:', first.min())
print('mean vertical:', first.mean(axis=0))
print('mean horizontal:', first.mean(axis=1))

[[-14  13  13  14 -11]
 [ 14  -2  13  -4  -4]
 [ 13  10   5 -15 -15]]
max: 14 min: -15
mean vertical: [  4.33333333   7.          10.33333333  -1.66666667 -10.        ]
mean horizontal: [ 3.   3.4 -0.4]


10. Задание
- даны две матрицы
- убедитесь, что их можно пермножить
- произведите операцию умножения матриц, если это возможно, иначе выведите ошибку

In [94]:
a = np.random.randint(-10, 10, (2, 5))
first_axis = np.random.randint(4, 6)
print(first_axis)
b = np.random.randint(-10, 10, (first_axis, 3))
if a.shape[1] == first_axis:
    print(a @ b)
else:
    print('traceback')
    

5
[[-84  21 -21]
 [ 34 -31  -7]]


11. Задание
- создайте матрицу 5 на 5 заполненную равномерным распределением с диапазоно 2-12
- заполните все элементы ниже главной диагонали нулями

In [99]:
mask = np.random.uniform(2, 12, (5,5))
print(mask, '\n')
mask[np.tril_indices(5, -1)] = 0
print(mask)

[[11.7516993   6.14459459  7.32788001 10.31842091  4.97231603]
 [ 8.76782407  8.20939579  8.3091281   6.91625086  2.38918889]
 [11.03867593  3.08975957  4.70298586  8.49362661  4.54681523]
 [10.79542262  8.93234998  5.1097531   9.40557474  6.1502076 ]
 [ 3.41394667  4.65751701  2.64677893  5.90179377  9.83536372]] 

[[11.7516993   6.14459459  7.32788001 10.31842091  4.97231603]
 [ 0.          8.20939579  8.3091281   6.91625086  2.38918889]
 [ 0.          0.          4.70298586  8.49362661  4.54681523]
 [ 0.          0.          0.          9.40557474  6.1502076 ]
 [ 0.          0.          0.          0.          9.83536372]]


12. Задание
- создайте матрицу 5 на 5 заполненную нормальным распределением с парметрами среднее 10 и отклонение 2
- заполните все элементы на главной диагонали нулями

In [91]:
mask = np.random.normal(10, 2, (5, 5))
di = np.diag_indices(5)
matrix = mask
mask[di] = 0

print(matrix)

[[ 0.         12.86127131 11.22168971  7.21720825 10.47671893]
 [11.96135823  0.         13.14356861  9.90337982 12.11014366]
 [13.13628799  7.28890965  0.          7.23622246 11.15415884]
 [ 9.35751857 10.12510034  9.94678946  0.         10.46373431]
 [13.25006165  9.11060909  9.34040538  9.6598091   0.        ]]


## 13. Задание
- дано два массива, проверить одинаковы ли они

In [102]:
a = np.random.randint(0,2,5)
print(a)
b = np.random.randint(0,2,5)
print(b)
equal = np.array_equal(a,b)
equal

[0 1 1 1 0]
[1 0 1 1 0]


False

14. Задание
- сгенерируйте матрицу случайного размера:
 - строк от 3 до 7
 - столбцов от 2 до 12
- сгенерируйте число N - размер выборки так, чтобы оно не превышало половину количества элементов сгенерированной матрицы, но было больше 0
- сделайте случайную выборку N элементов

In [125]:
r, c = np.random.randint(3,7), np.random.randint(2,12)
a = np.random.sample((r,c))
print(a)
N = np.random.randint(0, r*c/2) 
print(N)
sample = np.random.choice(a.reshape(r*c), N)
print(sample)

[[0.09276302 0.0772502  0.53037219 0.86408608]
 [0.29126194 0.60865055 0.5691283  0.72585249]
 [0.93778753 0.65489803 0.54313851 0.91065248]
 [0.76604798 0.19713809 0.97469657 0.70819056]]
7
[0.72585249 0.60865055 0.86408608 0.97469657 0.09276302 0.86408608
 0.76604798]


15. Задание
- дан вектор, проверить есть в нем Nan
- проверить есть в нем знак бесконечности
- заполнить их нулями

In [132]:
a = np.array([1, np.NaN, np.Inf], float)
print('is it NaN? ', np.isnan(a))
print('is it Infinity? ', np.isinf(a))
a

is it NaN?  [False  True False]
is it Infinity?  [False False  True]


array([ 1., nan, inf])

16. Задание
- сгенерировать массив с произвольным числом осей
- определить сколько у него осей

In [155]:
axis = np.random.randint(0, 10)
print(axis)
matrix = np.arange(axis**axis).reshape(*[axis]*axis)
print(matrix.ndim)

6
6


17. Задание
- сгенерируйте матрицу 10 на 3 с нормальным распределением, среднее 50, отклонение 10
- найдите индексы максимальных элементов в каждой строке
- найдите сами элементы

In [145]:
matrix = np.random.normal(50, 10, (10,3))
print(matrix)
indexes = matrix.argmax(axis = 1)
print(indexes)
print(matrix.max(axis=1))

[[59.50722007 55.64882258 43.601435  ]
 [56.64101752 58.81946836 40.94583216]
 [69.44451729 55.30175182 54.80710386]
 [42.44817153 57.14702188 32.49550562]
 [47.76582561 59.55932534 57.05173243]
 [43.96263667 55.42736882 56.24908581]
 [61.1270066  59.481786   50.71685145]
 [45.8277303  49.38359947 45.56134551]
 [60.70464341 60.40841661 63.36467888]
 [54.93177829 45.39530205 56.13291731]]
[0 1 0 1 1 2 0 1 2 2]
[59.50722007 58.81946836 69.44451729 57.14702188 59.55932534 56.24908581
 61.1270066  49.38359947 63.36467888 56.13291731]
