In [1]:
import numpy as np

1. Задание
- проверьте тип объекта python_list
- если это не numpy ndarray, то преобразуйте к нему
- проверьте, что на выходе вы получили объект python_list желаемого типа

In [6]:
python_list = [1, 12, 13, 45, 76, 45, 98, 0]
print(type(python_list))
python_list =np.array(python_list) 
print(type(python_list))

<class 'list'>
<class 'numpy.ndarray'>


2. Задание
- создайте одномерный массив numpy из 10 элементов заполненный числом 1.5

In [4]:
z =  np.full(10, 1.5)
print(z)

[1.5 1.5 1.5 1.5 1.5 1.5 1.5 1.5 1.5 1.5]


3. Задание
- создайте двумерный массив numpy из 25 элементов заполненный числом 0

In [8]:
z = np.zeros((2,25))
print(z)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0.]]


4. Задание
- создайте одномерный массив numpy из 12 элементов заполненный числом 1

In [9]:
ones = np.ones(10)
print(ones)

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


5. Задание
- преобразуйте массив из предыдущего задания к матрице 3 на 4
- выведите размерность полученного массива

In [11]:
ones = np.zeros((3,4))
ones.shape

(3, 4)

6. Задание
- создайте матрицу 4 на 5 заполненную числами от 1 до 20
- замените элемент в 3-й строке 4-м столбце на -99

In [14]:
Z = np.arange(1,21).reshape(4,5)
print(Z)
Z[2][3]=-99
print(Z)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]
[[  1   2   3   4   5]
 [  6   7   8   9  10]
 [ 11  12  13 -99  15]
 [ 16  17  18  19  20]]


7. Задание
- создайте вектор длинной 15 со случайными целыми числами в диапазоне от -10 до 10
- сделайте реверс вектора

In [16]:
first =  np.random.randint(-10, 10, 15)
print(first)
second = first[::-1]
print(second)

[-8  1 -9  2  2 -2 -7 -7  0 -1  5 -9 -7 -3  9]
[ 9 -3 -7 -9  5 -1  0 -7 -7 -2  2  2 -9  1 -8]


8. Задание
- создайте матрицу 5 на 5 со случайными целыми числами в диапазоне от -15 до 15
- замените отрицательные элементы на их квадраты

In [24]:
first = np.random.randint(-15, 15, 25).reshape(5,5)
print(first)
first=np.where(first >= 0, first, first**2)
print(first)

[[ -3 -10 -11  11 -12]
 [  7   3   9   2   2]
 [ 11   3   6  -5 -13]
 [  9 -14   4   6 -15]
 [ 11  -8  13  -9   1]]
[[  9 100 121  11 144]
 [  7   3   9   2   2]
 [ 11   3   6  25 169]
 [  9 196   4   6 225]
 [ 11  64  13  81   1]]


9. Задание
- создайте матрицу 3 на 5 со случайными целыми числами в диапазоне от -15 до 15
- найдите максимум и минимум
- найдите среднее по столбцам
- найдите среднее по строкам

In [27]:
first = np.random.randint(-15,15,15).reshape(3,5)
print('max =',first.max(),'  min = ',first.min())
print(np.mean(first, axis=0))
print(np.mean(first, axis=1))


max = 14   min =  -14
[ -6.33333333   5.33333333   6.         -11.33333333  -1.66666667]
[ 4.4 -6.2 -3. ]


10. Задание
- даны две матрицы
- убедитесь, что их можно пермножить
- произведите операцию умножения матриц, если это возможно, иначе выведите ошибку

In [39]:
a = np.random.randint(-10, 10, (2, 5))
first_axis = np.random.randint(4, 6)
print(first_axis)
b = np.random.randint(-10, 10, (first_axis, 3))
print('a = ',a)
print('b = ',b)
if first_axis==5 : 
    print(a @ b)
else:
    print('ERORR')

4
a =  [[ 3  1  8 -5  0]
 [ 5 -8 -9 -1 -6]]
b =  [[-8 -3 -7]
 [ 4  3 -2]
 [-6  5  6]
 [-2 -5  6]]
ERORR


11. Задание
- создайте матрицу 5 на 5 заполненную равномерным распределением с диапазоно 2-12
- заполните все элементы ниже главной диагонали нулями

In [44]:
mask = np.random.uniform(2, 12, (5,5))
mask[np.tril_indices(5, -1)] = 0

print(mask)

[[ 7.92010625 11.36560755  5.07377193  5.5451433   3.42716431]
 [ 0.          4.1085034   5.05344562  8.18278933  9.949788  ]
 [ 0.          0.          5.46467252 11.55888497  4.21476714]
 [ 0.          0.          0.         11.37666149  8.98377418]
 [ 0.          0.          0.          0.          3.84409421]]


12. Задание
- создайте матрицу 5 на 5 заполненную нормальным распределением с парметрами среднее 10 и отклонение 2
- заполните все элементы на главной диагонали нулями

In [51]:
mask = np.random.normal(10, 2, (5,5))
np.fill_diagonal(mask, 0)

print(mask)

[[ 0.         12.82128638  8.49602145  9.82423924 10.41807673]
 [12.93912744  0.         12.25587995 10.74667337 12.83488576]
 [ 4.82578851 12.27679585  0.         12.13315168 11.74028776]
 [11.55867347 10.23980665  8.94544285  0.          6.643776  ]
 [12.03479372 11.17143894 14.57082179 14.16699985  0.        ]]


13. Задание
- дано два массива, проверить одинаковы ли они

In [70]:
a = np.random.randint(0,2,5)
print(a)
b = np.random.randint(0,2,5)
print(b)
equal = np.array_equal(a, b)
print(equal)

[0 1 1 0 1]
[0 1 1 0 1]
True


14. Задание
- сгенерируйте матрицу случайного размера:
 - строк от 3 до 7
 - столбцов от 2 до 12
- сгенерируйте число N - размер выборки так, чтобы оно не превышало половину количества элементов сгенерированной матрицы, но было больше 0
- сделайте случайную выборку N элементов

In [75]:
r, c = np.random.randint(3, 7), np.random.randint(2,12)
a = np.random.randint(-20,20,(r,c)) 
print(a)
N = (r * c)//2
print(N)
sample = np.random.choice(a.ravel(),size=N )
print(sample)

[[-18  10 -19  -5   9]
 [-16   7 -18  -2 -12]
 [-13  12   6  -5 -10]
 [  2   2  -6   7   6]]
10
[-10 -19   2 -19   6 -18 -18 -12 -18  -5]


15. Задание
- дан вектор, проверить есть в нем Nan
- проверить есть в нем знак бесконечности
- заполнить их нулями

In [79]:
a = np.array([1, np.NaN, np.Inf], float)
print(np.isnan(a))
print(np.isinf(a))
a[1:]=0
print(a)

[False  True False]
[False False  True]
[1. 0. 0.]


16. Задание
- сгенерировать массив с произвольным числом осей
- определить сколько у него осей

In [80]:
axis = np.random.randint(0,8)
print(axis)
matrix = 
print(...)

SyntaxError: invalid syntax (TEMP/ipykernel_15104/3650866403.py, line 3)

17. Задание
- сгенерируйте матрицу 10 на 3 с нормальным распределением, среднее 50, отклонение 10
- найдите индексы максимальных элементов в каждой строке
- найдите сами элементы

In [83]:
matrix = np.random.normal(50, 10, (10,3))
print(matrix)
indexes = np.argmax(matrix, axis=1)
print(indexes)
print(np.amax(matrix, axis=1))

[[30.73025906 40.90631352 39.95558797]
 [51.79175254 41.74779145 44.56792504]
 [38.73284375 51.43317807 58.10537794]
 [56.64429624 48.4979982  54.17155048]
 [50.18333487 43.32305745 55.34790462]
 [46.91535895 50.93002185 53.342039  ]
 [49.82315325 39.2204469  58.43315731]
 [49.79818856 41.07638651 56.1738985 ]
 [46.54871159 33.2682273  44.25880325]
 [50.07869666 56.98230009 59.21777598]]
[1 0 2 0 2 2 2 2 0 2]
[40.90631352 51.79175254 58.10537794 56.64429624 55.34790462 53.342039
 58.43315731 56.1738985  46.54871159 59.21777598]
