In [8]:
import numpy as np

1. Задание
- проверьте тип объекта python_list
- если это не numpy ndarray, то преобразуйте к нему
- проверьте, что на выходе вы получили объект python_list желаемого типа

In [10]:
python_list = [1, 12, 13, 45, 76, 45, 98, 0]
print(type(python_list))
if type(python_list) is not type(np.ndarray):
    python_list = np.array(python_list)
    print(type(python_list))

<class 'list'>
<class 'numpy.ndarray'>


2. Задание
- создайте одномерный массив numpy из 10 элементов заполненный числом 1.5

In [11]:
z = np.ndarray((10))
z.fill(1.5)
print(z)

[1.5 1.5 1.5 1.5 1.5 1.5 1.5 1.5 1.5 1.5]


3. Задание
- создайте двумерный массив numpy из 25 элементов заполненный числом 0

In [12]:
z = np.ndarray((5,5))
z.fill(0)
print(z)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


4. Задание
- создайте одномерный массив numpy из 12 элементов заполненный числом 1

In [15]:
ones = np.ndarray((12))
ones.fill(1)
print(ones)

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


5. Задание
- преобразуйте массив из предыдущего задания к матрице 3 на 4
- выведите размерность полученного массива

In [17]:
ones = ones.reshape((3,4))
ones.shape

(3, 4)

6. Задание
- создайте матрицу 4 на 5 заполненную числами от 1 до 20
- замените элемент в 3-й строке 4-м столбце на -99

In [27]:
Z = np.array(range(1,21)).reshape((4,5))
print(Z)
Z[2,3] = -99
print(Z)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]
[[  1   2   3   4   5]
 [  6   7   8   9  10]
 [ 11  12  13 -99  15]
 [ 16  17  18  19  20]]


7. Задание
- создайте вектор длинной 15 со случайными целыми числами в диапазоне от -10 до 10
- сделайте реверс вектора

In [36]:
first = np.random.randint(-10, 10, 15)
print(first)
second = first[::-1]
print(second)

[-6 -5 -3 -9  2 -1 -7  4 -2  4  9  1  6  9 -9]
[-9  9  6  1  9  4 -2  4 -7 -1  2 -9 -3 -5 -6]


8. Задание
- создайте матрицу 5 на 5 со случайными целыми числами в диапазоне от -15 до 15
- замените отрицательные элементы на их квадраты

In [42]:
first = np.random.randint(-15, 15, 25).reshape(5,5)
print(first)
second = np.where(first < 0, first * first, first)
print(second)

[[ -8 -15  -3 -15 -13]
 [  3   1  -2  12   2]
 [ -8  10   4  11   7]
 [  3  -3   8  -7   9]
 [ -8   4   1   3  -6]]
[[ 64 225   9 225 169]
 [  3   1   4  12   2]
 [ 64  10   4  11   7]
 [  3   9   8  49   9]
 [ 64   4   1   3  36]]


9. Задание
* создайте матрицу 3 на 5 со случайными целыми числами в диапазоне от -15 до 15
- найдите максимум и минимум
- найдите среднее по столбцам
- найдите среднее по строкам

In [43]:
first = np.random.randint(-15, 15, 15).reshape(3,5)
print(first)
print(first.max())
print(first.min())
print(first.mean(0))
print(first.mean(1))

[[ 14   1 -15   6  10]
 [  2   8   0   2 -12]
 [  8   7 -13 -15 -15]]
14
-15
[ 8.          5.33333333 -9.33333333 -2.33333333 -5.66666667]
[ 3.2  0.  -5.6]


10. Задание
- даны две матрицы
- убедитесь, что их можно пермножить
- произведите операцию умножения матриц, если это возможно, иначе выведите ошибку

In [52]:
a = np.random.randint(-10, 10, (2, 5))
first_axis = np.random.randint(4, 6)
b = np.random.randint(-10, 10, (first_axis, 3))
if a.shape[1] > b.shape[0]:
    print(a @ b)
else:
    print("ошибка")

ошибка


11. Задание
- создайте матрицу 5 на 5 заполненную равномерным распределением с диапазоно 2-12
- заполните все элементы ниже главной диагонали нулями

In [59]:
mask = np.random.uniform(2, 12, (5, 5)) 
mask[np.tril_indices(mask.shape[0], -1)] = -1

print(mask)

[[ 9.3644026   7.79204479 10.08965367  5.74938636  8.91716017]
 [-1.          5.78212538  5.81273871 10.96234732 10.98882155]
 [-1.         -1.          2.92659868  5.03512595  3.69046254]
 [-1.         -1.         -1.          7.57619411  2.98246146]
 [-1.         -1.         -1.         -1.          3.9723598 ]]


12. Задание
- создайте матрицу 5 на 5 заполненную нормальным распределением с парметрами среднее 10 и отклонение 2
- заполните все элементы на главной диагонали нулями

In [73]:
mask = f = np.random.normal(10,2, 25).reshape(5,5)
mask[np.diag_indices(mask.shape[0])] = 0

print(mask)

[[ 0.          7.72552056  9.34318091 14.92855296 10.79733375]
 [12.77341876  0.          8.5398054  10.4065298  10.83770999]
 [ 7.40816283 12.25751646  0.          6.88310668  9.30014331]
 [ 6.48622981 12.57147327  8.47041939  0.          5.16661393]
 [10.68673388  9.87583181 11.4860628  10.03769708  0.        ]]


13. Задание
- дано два массива, проверить одинаковы ли они

In [75]:
a = np.random.randint(0,2,5)
print(a)
b = np.random.randint(0,2,5)
print(b)
equal = a==b
print(equal)

[1 0 1 0 1]
[0 0 0 1 0]
[False  True False False False]


14. Задание
- сгенерируйте матрицу случайного размера:
 - строк от 3 до 7
 - столбцов от 2 до 12
- сгенерируйте число N - размер выборки так, чтобы оно не превышало половину количества элементов сгенерированной матрицы, но было больше 0
- сделайте случайную выборку N элементов

In [89]:
r, c = np.random.randint(3,7), np.random.randint(2,12)
a = np.ndarray((r,c))
print(a)
N = np.random.randint(0,a.size /2)
print(N)
sample = np.random.choice(a.flatten(),N)
print(sample)

[[ 7.97579888e-312  7.97579889e-312  7.97579889e-312  7.97579889e-312
   7.97579889e-312  7.97579889e-312  7.97579889e-312  7.97579889e-312
   7.97579889e-312]
 [-2.96954318e-311  0.00000000e+000  0.00000000e+000  0.00000000e+000
   6.95188443e-310  2.56914136e-322  7.97579884e-312  7.97579889e-312
   7.97579884e-312]
 [ 7.97579884e-312  7.97579889e-312  7.97579884e-312  7.97579889e-312
   7.97579889e-312  7.97579770e-312  7.97579889e-312  7.97579884e-312
   7.97579884e-312]
 [ 7.97579884e-312  7.97579888e-312  7.97579733e-312  7.97579888e-312
   7.97579888e-312  7.97579889e-312  7.97579888e-312  7.97579888e-312
   7.97579888e-312]
 [ 7.97579888e-312  7.97579889e-312  7.97579888e-312  7.97579889e-312
   7.97579843e-312  7.97579889e-312  7.97579856e-312  7.97579888e-312
   7.97579833e-312]
 [ 7.97579888e-312  7.97579964e-312  7.97579888e-312  7.97579888e-312
   7.97579888e-312  7.97579889e-312  7.97579889e-312  7.97579888e-312
   7.97579889e-312]]
3
[7.97579888e-312 7.97579889e-312 7.97

15. Задание
- дан вектор, проверить есть в нем Nan
- проверить есть в нем знак бесконечности
- заполнить их нулями

In [95]:
a = np.array([1, np.NaN, np.Inf], float)
a = np.where(np.isnan(a) | np.isinf(a),0,a)
print(a)

[1. 0. 0.]


16. Задание
- сгенерировать массив с произвольным числом осей
- определить сколько у него осей

In [109]:
axis = np.random.randint(1,10)
print(axis)
matrix = np.ndarray(tuple(range(axis)))
print(matrix.ndim)

3
3


17. Задание
- сгенерируйте матрицу 10 на 3 с нормальным распределением, среднее 50, отклонение 10
- найдите индексы максимальных элементов в каждой строке
- найдите сами элементы

In [144]:
matrix = np.random.normal(50, 10, (10,3)).astype(int) 
print(matrix)
indexes = matrix.argmax(1)
print(indexes)
print(matrix[0][indexes])

[[61 46 55]
 [49 58 56]
 [48 62 63]
 [45 52 51]
 [46 65 46]
 [50 39 40]
 [34 58 37]
 [66 47 48]
 [57 51 50]
 [64 50 61]]
[0 1 2 1 1 0 1 0 0 0]
[61 46 55 46 46 61 46 61 61 61]
