In [1]:
import numpy as np
import random

In [2]:
python_list = [1, 12, 13, 45, 76, 45, 98, 0]
print(type(python_list))
if type(python_list) is not 'numpy.ndarray':
    python_list = np.array(python_list)
print(type(python_list))

<>:3: SyntaxWarning: "is not" with a literal. Did you mean "!="?
<>:3: SyntaxWarning: "is not" with a literal. Did you mean "!="?


<class 'list'>


<ipython-input-2-b708454e0338>:3: SyntaxWarning: "is not" with a literal. Did you mean "!="?
  if type(python_list) is not 'numpy.ndarray':


<class 'numpy.ndarray'>


In [3]:
z = np.full(10,1.5)
print(z)

[1.5 1.5 1.5 1.5 1.5 1.5 1.5 1.5 1.5 1.5]


In [4]:
z = np.zeros((2, 25))
print(z)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0.]]


In [5]:
ones = np.full(12,1)
print(ones)

[1 1 1 1 1 1 1 1 1 1 1 1]


In [6]:
ones = ones.reshape(3,4)
print(ones.shape)

(3, 4)


In [7]:
Z = np.arange(1,21,1).reshape(4,5)
print(Z)
Z[2][3]=-99
print(Z)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]
[[  1   2   3   4   5]
 [  6   7   8   9  10]
 [ 11  12  13 -99  15]
 [ 16  17  18  19  20]]


In [8]:
first = np.random.randint(-10, 10, 15)
print(first)
second = first[::-1]
print(second)

[ 5 -3 -9  8 -8 -7 -2 -1  4  3  2  1  0  8 -9]
[-9  8  0  1  2  3  4 -1 -2 -7 -8  8 -9 -3  5]


In [9]:
first = np.random.randint(-15, 15, 25).reshape(5,5)
print(first)
first=np.array([i*i if i<0 else i for i in first.ravel()]).reshape(5,5)
print(first)

[[ -8   8  -8 -13   3]
 [-11  12 -10  12  -7]
 [-15  -7   6 -15 -12]
 [ -9  11   7 -15 -13]
 [ 14   7  -2  -8  -4]]
[[ 64   8  64 169   3]
 [121  12 100  12  49]
 [225  49   6 225 144]
 [ 81  11   7 225 169]
 [ 14   7   4  64  16]]


In [10]:
first = np.random.randint(-15, 15, 15).reshape(3,5)
print(first)
print(first.max(),first.min(),first.mean(axis=0),first.mean(axis=1))

[[  0   2 -13  -7  -8]
 [  4   5  10 -15  -1]
 [ 14 -12  -9 -12  -3]]
14 -15 [  6.          -1.66666667  -4.         -11.33333333  -4.        ] [-5.2  0.6 -4.4]


In [11]:
a = np.random.randint(-10, 10, (2, 5))
first_axis = np.random.randint(4, 6)
b = np.random.randint(-10, 10, (first_axis, 3))
print(a)
print(b)
print(a.shape,b.shape)
if a.shape[1]==b.shape[0] :
    print(a.dot(b))
else:
    print("Ошибка!")

[[  1   0   3  -7 -10]
 [  5  -4  -1   1  -9]]
[[ -6   8   4]
 [ -5   9  -3]
 [  4   7   9]
 [-10   8   4]]
(2, 5) (4, 3)
Ошибка!


In [12]:
mask = np.random.uniform(2, 12, (5, 5)) 
print(mask)
mask[np.tril_indices(5, -1)] = 0
matrix = mask
print(matrix)

[[ 7.06701872  3.59655659  6.41418417 10.22936981  4.55008583]
 [ 7.96916149  9.97171939  4.79134822  7.02051113  8.97131958]
 [ 7.55660222  7.16789098 10.2498419   8.71048664  6.4692685 ]
 [11.06650925  8.86514045  3.69571205  9.16825325  5.01901031]
 [11.8748883   9.44007247  8.22611336 10.66717289  6.14917873]]
[[ 7.06701872  3.59655659  6.41418417 10.22936981  4.55008583]
 [ 0.          9.97171939  4.79134822  7.02051113  8.97131958]
 [ 0.          0.         10.2498419   8.71048664  6.4692685 ]
 [ 0.          0.          0.          9.16825325  5.01901031]
 [ 0.          0.          0.          0.          6.14917873]]


In [13]:
mask =np.random.normal(10, 2, 25).reshape(5,5)
print(mask)
mask[np.diag_indices(5)] = 0
matrix = mask
print(matrix)

[[ 9.91316714  6.34550372  7.76155774 10.54823626 11.31871242]
 [ 5.31480719  6.91699947 10.31226178  8.64243223 10.23317928]
 [ 8.69067595 10.44768691  9.0068715   7.82252434  9.8078059 ]
 [12.21729204 10.13425224  9.94251486 12.56975161  7.51103498]
 [ 9.41256464  9.18163338 14.53528573 10.53827169  9.12362772]]
[[ 0.          6.34550372  7.76155774 10.54823626 11.31871242]
 [ 5.31480719  0.         10.31226178  8.64243223 10.23317928]
 [ 8.69067595 10.44768691  0.          7.82252434  9.8078059 ]
 [12.21729204 10.13425224  9.94251486  0.          7.51103498]
 [ 9.41256464  9.18163338 14.53528573 10.53827169  0.        ]]


In [14]:
a = np.random.randint(0,2,5)
print(a)
b = np.random.randint(0,2,5)
print(b)
equal = np.array_equal(a,b)
print(equal)

[0 1 1 1 0]
[1 1 1 1 0]
False


In [15]:
r, c = random.randint(3,7),random.randint(2,12)
a = np.random.randint(-15, 15, r*c).reshape(r,c)
print(a)
N = r*c//2
print(N)
s=set()
count=0
sample=[]
while True:
    i, j = random.randint(0,r-1),random.randint(0,c-1)
    if (i, j) not in s:
        s.add((i, j))
        count+=1
        sample.append(a[i][j])
    if N == count:
        break
print(sample)

[[-13   8   2  13  -5   8   1  11   3  -5]
 [-12  12   0   4  -3 -12  -6  14   0   1]
 [ -3   4 -10   9   4   0   8 -11 -11   5]
 [ -7  -4  -7  -7   3  -7  13 -14   1  13]]
20
[-11, -7, 8, 2, 13, 4, 13, 4, 0, -4, 1, -5, 9, -11, 1, 14, -5, -14, 0, 8]


In [29]:
a = np.array([1, np.NaN, np.Inf], float)
print(a)
a[np.isnan(a)]=0
a[np.isinf(a)]=0
print(a)


[ 1. nan inf]
[1. 0. 0.]


In [55]:
axis = random.randint(1,5)
print(axis)
matrix = np.arange(np.math.factorial(axis)).reshape([i for i in range(1,axis+1)])
print(matrix)
print(matrix.ndim)

2
[[0 1]]
2


In [34]:
matrix = np.random.normal(50, 10, (10,3))
print(matrix)
indexes =np.argmax(matrix,axis=1) 
print(indexes)
print(np.amax(matrix,axis=1))

[[60.31706356 56.91231409 56.07774197]
 [41.01603076 51.89106166 56.70132702]
 [63.08147555 48.39991647 43.32159037]
 [38.3121983  62.57399301 57.61303084]
 [40.70319707 50.69338586 60.46488882]
 [56.54690773 40.43941707 47.10681669]
 [57.85355808 64.56475082 62.27495569]
 [55.56369408 19.60753686 51.00817838]
 [71.97141348 47.91661657 45.45307281]
 [42.54217472 36.90909217 70.41712757]]
[0 2 0 1 2 0 1 0 0 2]
[60.31706356 56.70132702 63.08147555 62.57399301 60.46488882 56.54690773
 64.56475082 55.56369408 71.97141348 70.41712757]
