In [2]:
import numpy as np

1. Задание
- проверьте тип объекта python_list
- если это не numpy ndarray, то преобразуйте к нему
- проверьте, что на выходе вы получили объект python_list желаемого типа

In [3]:
python_list = [1, 12, 13, 45, 76, 45, 98, 0]
print(type(python_list))
if type(python_list) != type(np.array([1,2,3])):
    python_list = np.array([1, 12, 13, 45, 76, 45, 98, 0])
print(type(python_list))

<class 'list'>
<class 'numpy.ndarray'>


2. Задание
- создайте одномерный массив numpy из 10 элементов заполненный числом 1.5

In [4]:
z = np.array([1.5 for i in range(10)])
print(z)

[1.5 1.5 1.5 1.5 1.5 1.5 1.5 1.5 1.5 1.5]


3. Задание
- создайте двумерный массив numpy из 25 элементов заполненный числом 0

In [5]:
z = np.zeros((5, 5))
print(z)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


4. Задание
- создайте одномерный массив numpy из 12 элементов заполненный числом 1

In [6]:
ones = np.ones(12, int)
print(ones)

[1 1 1 1 1 1 1 1 1 1 1 1]


5. Задание
- преобразуйте массив из предыдущего задания к матрице 3 на 4
- выведите размерность полученного массива

In [7]:
ones = ones.reshape(3,4)
print(ones.shape)

(3, 4)


6. Задание
- создайте матрицу 4 на 5 заполненную числами от 1 до 20
- замените элемент в 3-й строке 4-м столбце на -99

In [8]:
Z = np.arange(1, 21, 1).reshape(4,5)
print(Z)
Z[2,3] = -99
print(Z)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]
[[  1   2   3   4   5]
 [  6   7   8   9  10]
 [ 11  12  13 -99  15]
 [ 16  17  18  19  20]]


7. Задание
- создайте вектор длинной 15 со случайными целыми числами в диапазоне от -10 до 10
- сделайте реверс вектора

In [9]:
first = np.random.randint(-10, 10, 15)
print(first)
second = first[::-1]
print(second)

[  1   8   1   9   4   2  -6   1 -10  -5  -2   2   8  -9   2]
[  2  -9   8   2  -2  -5 -10   1  -6   2   4   9   1   8   1]


8. Задание
- создайте матрицу 5 на 5 со случайными целыми числами в диапазоне от -15 до 15
- замените отрицательные элементы на их квадраты

In [10]:
first = np.random.randint(-15, 15, 25).reshape(5,5)
print(first)
first = np.where(first < 0, first ** 2, first)
print(first)

[[ -1   4  12  13   5]
 [ -4   8 -13   3   8]
 [ -3  -7  -8 -14   5]
 [ 11 -10   2 -11   8]
 [  0 -13  13  -8 -12]]
[[  1   4  12  13   5]
 [ 16   8 169   3   8]
 [  9  49  64 196   5]
 [ 11 100   2 121   8]
 [  0 169  13  64 144]]


9. Задание
- создайте матрицу 3 на 5 со случайными целыми числами в диапазоне от -15 до 15
- найдите максимум и минимум
- найдите среднее по столбцам
- найдите среднее по строкам

In [11]:
first = np.random.randint(-15, 15, 15).reshape(3,5)
print(first)
print(first.max())
print(first.min())
print(np.mean(first, axis=0))
print(np.mean(first, axis=1, keepdims = True))

[[  6  -1   2   4   9]
 [  6 -15 -11   2  -1]
 [  3   6  -1  -4  11]]
11
-15
[ 5.         -3.33333333 -3.33333333  0.66666667  6.33333333]
[[ 4. ]
 [-3.8]
 [ 3. ]]


10. Задание
- даны две матрицы
- убедитесь, что их можно перемножить
- произведите операцию умножения матриц, если это возможно, иначе выведите ошибку

In [12]:
import traceback as TB
a = np.random.randint(-10, 10, (2, 5))
first_axis = np.random.randint(4, 6)
b = np.random.randint(-10, 10, (first_axis, 3))
a_cols, a_rows = a.shape
b_cols, b_rows = b.shape
if a_cols == b_rows:
    print(a @ b)
else:
    print("Ошибка:\n", TB.format_exc())
    

Ошибка:
 NoneType: None



11. Задание
- создайте матрицу 5 на 5 заполненную равномерным распределением с диапазоном 2-12
- заполните все элементы ниже главной диагонали нулями

In [13]:
mask = np.linspace(2, 12, 25).reshape(5,5)
matrix = mask.copy()
matrix[np.tril_indices(matrix.shape[0], -1)] = 0

print(matrix)

[[ 2.          2.41666667  2.83333333  3.25        3.66666667]
 [ 0.          4.5         4.91666667  5.33333333  5.75      ]
 [ 0.          0.          7.          7.41666667  7.83333333]
 [ 0.          0.          0.          9.5         9.91666667]
 [ 0.          0.          0.          0.         12.        ]]


12. Задание
- создайте матрицу 5 на 5 заполненную нормальным распределением с парметрами среднее 10 и отклонение 2
- заполните все элементы на главной диагонали нулями

In [16]:
mask = np.random.normal(10, 2, (5,5))
matrix = mask.copy()
matrix[np.diag_indices(matrix.shape[0])] = 0

print(matrix)

[[ 0.         11.36173105  6.7402793   8.17221732 12.27853604]
 [ 8.472255    0.          8.11683358 11.9007047  12.44620796]
 [11.57158374 11.94478374  0.          8.50439505 12.83912319]
 [11.94046684 12.16194725  8.75240452  0.          9.13760981]
 [13.42320754  7.31427126 11.08302544  7.78806653  0.        ]]


13. Задание
- дано два массива, проверить одинаковы ли они

In [23]:
a = np.random.randint(0,2,5)
print(a)
b = np.random.randint(0,2,5)
print(b)
equal = np.array_equal(a, b)
print(equal)

[0 1 0 0 0]
[0 1 1 0 1]


False

14. Задание
- сгенерируйте матрицу случайного размера:
 - строк от 3 до 7
 - столбцов от 2 до 12
- сгенерируйте число N - размер выборки так, чтобы оно не превышало половину количества элементов сгенерированной матрицы, но было больше 0
- сделайте случайную выборку N элементов

In [44]:
import random
r, c = np.random.randint(3, 7), np.random.randint(2, 12)
a = np.arange(c*r).reshape(c, r)
print(a)
N = np.random.randint(1, c*r/2)
print(N)
sample = np.random.choice(len(a), N)
print(sample)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]
3
[4 4 3]


15. Задание
- дан вектор, проверить есть в нем Nan
- проверить есть в нем знак бесконечности
- заполнить их нулями

In [47]:
a = np.array([1, np.NaN, np.Inf], float)
print(a)
b = np.isnan(np.sum(a))
print(b)
p_inf = float('inf')
print(True if p_inf in a else False)
for el in range(len(a)):
    if a[el] == p_inf:
        a[el] = 0
print(a)

[ 1. nan inf]
True
True
[ 1. nan  0.]


16. Задание
- сгенерировать массив с произвольным числом осей
- определить сколько у него осей

In [ ]:
axis = np.ndim
print(axis)
#matrix = 
print(...)

17. Задание
- сгенерируйте матрицу 10 на 3 с нормальным распределением, среднее 50, отклонение 10
- найдите индексы максимальных элементов в каждой строке
- найдите сами элементы

In [ ]:
matrix = np.random.normal(50, 10, (10,3))
print(matrix)
#indexes = 
#print(indexes)
#print(...)