In [6]:
import numpy as np

1. Задание
- проверьте тип объекта python_list
- если это не numpy ndarray, то преобразуйте к нему
- проверьте, что на выходе вы получили объект python_list желаемого типа

In [8]:
python_list = [1, 12, 13, 45, 76, 45, 98, 0]
print(type(python_list))
if type(python_list) is not type(np.ndarray):
    python_list = np.array(python_list)
    print(type(python_list))

<class 'list'>
<class 'numpy.ndarray'>


2. Задание
- создайте одномерный массив numpy из 10 элементов заполненный числом 1.5

In [10]:
z = np.ndarray((10))
z.fill(1.5)
print(z)

[1.5 1.5 1.5 1.5 1.5 1.5 1.5 1.5 1.5 1.5]


3. Задание
- создайте двумерный массив numpy из 25 элементов заполненный числом 0

In [11]:
z = np.ndarray((5,5))
z.fill(0)
print(z)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


4. Задание
- создайте одномерный массив numpy из 12 элементов заполненный числом 1

In [12]:
ones = np.ndarray((12))
ones.fill(1)
print(ones)

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


5. Задание
- преобразуйте массив из предыдущего задания к матрице 3 на 4
- выведите размерность полученного массива

In [13]:
ones = ones.reshape((3,4))
ones.shape

(3, 4)

6. Задание
- создайте матрицу 4 на 5 заполненную числами от 1 до 20
- замените элемент в 3-й строке 4-м столбце на -99

In [14]:
Z = np.array(range(1,21)).reshape((4,5))
print(Z)
Z[2,3] = -99
print(Z)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]
[[  1   2   3   4   5]
 [  6   7   8   9  10]
 [ 11  12  13 -99  15]
 [ 16  17  18  19  20]]


7. Задание
- создайте вектор длинной 15 со случайными целыми числами в диапазоне от -10 до 10
- сделайте реверс вектора

In [15]:
first = np.random.randint(-10, 10, 15)
print(first)
second = first[::-1]
print(second)

[ 4  3  9  4  4  8  1 -2 -8  8 -8 -7 -3 -8  9]
[ 9 -8 -3 -7 -8  8 -8 -2  1  8  4  4  9  3  4]


8. Задание
- создайте матрицу 5 на 5 со случайными целыми числами в диапазоне от -15 до 15
- замените отрицательные элементы на их квадраты

In [16]:
first = np.random.randint(-15, 15, 25).reshape(5,5)
print(first)
second = np.where(first < 0, first * first, first)
print(first)

[[  2 -12  13  -8  10]
 [  6   3   5   3   0]
 [ 14   6 -15  11  10]
 [ 11  -2  13 -12  -7]
 [ -8  -3 -11  10 -15]]
[[  2 -12  13  -8  10]
 [  6   3   5   3   0]
 [ 14   6 -15  11  10]
 [ 11  -2  13 -12  -7]
 [ -8  -3 -11  10 -15]]


9. Задание
- создайте матрицу 3 на 5 со случайными целыми числами в диапазоне от -15 до 15
- найдите максимум и минимум
- найдите среднее по столбцам
- найдите среднее по строкам

In [17]:
first = np.random.randint(-15, 15, 15).reshape(3,5)
print(first)
print(first.max())
print(first.min())
print(first.mean(0))
print(first.mean(1))



[[-15   6   2   3  -8]
 [ 14   7 -12  -2  12]
 [  2  -7  10   2  12]]
14
-15
[0.33333333 2.         0.         1.         5.33333333]
[-2.4  3.8  3.8]


10. Задание
- даны две матрицы
- убедитесь, что их можно пермножить
- произведите операцию умножения матриц, если это возможно, иначе выведите ошибку

In [18]:
a = np.random.randint(-10, 10, (2, 5))
first_axis = np.random.randint(4, 6)
b = np.random.randint(-10, 10, (first_axis, 3))
if a.shape[1] == b.shape[0]:
    print(a @ b)
else:
    print("ошибка")

ошибка


11. Задание
- создайте матрицу 5 на 5 заполненную равномерным распределением с диапазоно 2-12
- заполните все элементы ниже главной диагонали нулями

In [19]:
mask = np.random.uniform(2, 12, (5, 5)) 
mask[np.tril_indices(mask.shape[0], -1)] = 0

print(mask)

[[ 9.2100844   3.50089313 10.20536248  8.68024948 10.88132575]
 [ 0.          4.33409912  7.56655632  7.7462597   9.53943801]
 [ 0.          0.          2.43949394  6.53629363  3.15721657]
 [ 0.          0.          0.          2.27800496  5.66815189]
 [ 0.          0.          0.          0.          9.14753241]]


12. Задание
- создайте матрицу 5 на 5 заполненную нормальным распределением с парметрами среднее 10 и отклонение 2
- заполните все элементы на главной диагонали нулями

In [ ]:
mask = f = np.random.normal(10,2, 25).reshape(5,5)
mask[np.diag_indices(mask.shape[0])] = 0

print(mask)

13. Задание
- дано два массива, проверить одинаковы ли они

In [20]:
a = np.random.randint(0,2,5)
print(a)
b = np.random.randint(0,2,5)
print(b)
equal = np.array_equal(a, b) 
print(equal)

[0 1 1 0 0]
[0 0 0 1 0]
False


14. Задание
- сгенерируйте матрицу случайного размера:
 - строк от 3 до 7
 - столбцов от 2 до 12
- сгенерируйте число N - размер выборки так, чтобы оно не превышало половину количества элементов сгенерированной матрицы, но было больше 0
- сделайте случайную выборку N элементов

In [21]:
r, c = np.random.randint(3,7), np.random.randint(2,12)
a = np.ndarray((r,c))
print(a)
N = np.random.randint(0,a.size /2)
print(N)
sample = np.random.choice(a.flatten(),N)
print(sample)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
5
[1. 1. 1. 1. 1.]


15. Задание
- дан вектор, проверить есть в нем Nan
- проверить есть в нем знак бесконечности
- заполнить их нулями

In [22]:
a = np.array([1, np.NaN, np.Inf], float)
a = np.where(np.isnan(a) | np.isinf(a),0,a)
print(a)

[1. 0. 0.]


16. Задание
- сгенерировать массив с произвольным числом осей
- определить сколько у него осей

In [23]:
axis = np.random.randint(1,10)
print(axis)
matrix = np.ndarray(tuple(range(axis)))
print(matrix.ndim)

8
8


17. Задание
- сгенерируйте матрицу 10 на 3 с нормальным распределением, среднее 50, отклонение 10
- найдите индексы максимальных элементов в каждой строке
- найдите сами элементы

In [24]:
matrix = np.random.normal(50, 10, (10,3)).astype(int) 
print(matrix)
indexes = matrix.argmax(1)
print(indexes)
print(matrix.max(1))

[[55 53 46]
 [58 50 54]
 [57 61 53]
 [43 40 40]
 [46 52 39]
 [56 65 45]
 [51 66 23]
 [50 42 61]
 [62 41 29]
 [61 50 45]]
[0 0 1 0 1 1 1 2 0 0]
[55 58 61 43 52 65 66 61 62 61]
