In [3]:
import numpy as np

1. Задание
- проверьте тип объекта python_list
- если это не numpy ndarray, то преобразуйте к нему
- проверьте, что на выходе вы получили объект python_list желаемого типа

In [5]:
python_list = [1, 12, 13, 45, 76, 45, 98, 0]
print(type(python_list))
python_list = np.array(python_list)
print(type(python_list))

<class 'list'>
<class 'numpy.ndarray'>


2. Задание
- создайте одномерный массив numpy из 10 элементов заполненный числом 1.5

In [6]:
z = np.full(10, 1.5)
print(z)

[1.5 1.5 1.5 1.5 1.5 1.5 1.5 1.5 1.5 1.5]


3. Задание
- создайте двумерный массив numpy из 25 элементов заполненный числом 0

In [8]:
z = np.zeros((2, 25))
print(z)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0.]]


4. Задание
- создайте одномерный массив numpy из 12 элементов заполненный числом 1

In [10]:
ones = np.ones(12)
print(ones)

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


5. Задание
- преобразуйте массив из предыдущего задания к матрице 3 на 4
- выведите размерность полученного массива

In [11]:
ones = ones.reshape((3, 4))
ones.shape

(3, 4)

6. Задание
- создайте матрицу 4 на 5 заполненную числами от 1 до 20
- замените элемент в 3-й строке 4-м столбце на -99

In [12]:
Z = np.arange(1, 21).reshape(4, 5)
print(Z)
Z[2, 3] = -99
print(Z)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]
[[  1   2   3   4   5]
 [  6   7   8   9  10]
 [ 11  12  13 -99  15]
 [ 16  17  18  19  20]]


7. Задание
- создайте вектор длинной 15 со случайными целыми числами в диапазоне от -10 до 10
- сделайте реверс вектора

In [15]:
first = np.random.randint(-10, 10, 15)
print(first)
second = first[::-1]
print(second)

[-6  9 -6 -3 -5 -7 -1  1  3 -4  2  5  7  6 -4]
[-4  6  7  5  2 -4  3  1 -1 -7 -5 -3 -6  9 -6]


8. Задание
- создайте матрицу 5 на 5 со случайными целыми числами в диапазоне от -15 до 15
- замените отрицательные элементы на их квадраты

In [17]:
first = np.random.randint(-15, 15, 25).reshape(5, 5)
print(first)
first = np.where(first >= 0, first, first**2)
print(first)

[[12 -2 -9 -9  4]
 [-5 -3  0 11 12]
 [ 9 13  8 12 -7]
 [-8 -9 14 -3  2]
 [-8 -1 -4 -3 -1]]
[[12  4 81 81  4]
 [25  9  0 11 12]
 [ 9 13  8 12 49]
 [64 81 14  9  2]
 [64  1 16  9  1]]


9. Задание
- создайте матрицу 3 на 5 со случайными целыми числами в диапазоне от -15 до 15
- найдите максимум и минимум
- найдите среднее по столбцам
- найдите среднее по строкам

In [20]:
first = np.random.randint(-15, 15, 15).reshape(3, 5)
print(first)
print(f"max = {first.max()}; min - {first.min()};")
print(np.mean(first, axis=0))
print(np.mean(first, axis=1))


[[  3 -14  13  -9  12]
 [ -5   1   3  -6   3]
 [  3  13  -5  10  -1]]
max = 13; min - -14;
[ 0.33333333  0.          3.66666667 -1.66666667  4.66666667]
[ 1.  -0.8  4. ]


10. Задание
- даны две матрицы
- убедитесь, что их можно пермножить
- произведите операцию умножения матриц, если это возможно, иначе выведите ошибку

In [3]:
a = np.random.randint(-10, 10, (2, 5))
first_axis = np.random.randint(4, 6)
print(first_axis)
b = np.random.randint(-10, 10, (first_axis, 3))
print('a = ',a)
print('b = ',b)
if first_axis==5 : 
    print(a @ b)
else:
    print('ERORR')

5
a =  [[-1  0  0  0 -4]
 [-8  3 -7  4  2]]
b =  [[-6  9  3]
 [ 9  7 -4]
 [ 3 -1 -9]
 [ 8 -8  5]
 [ 7 -1 -2]]
[[-22  -5   5]
 [100 -78  43]]


11. Задание
- создайте матрицу 5 на 5 заполненную равномерным распределением с диапазоно 2-12
- заполните все элементы ниже главной диагонали нулями

In [6]:
mask = np.random.uniform(2, 12, (5,5))
mask[np.tril_indices(5, -1)] = 0

print(mask)

[[ 7.46661456  2.74228464  6.46365292 11.57467534  3.72174496]
 [ 0.          7.98833153 10.32534704  3.10539402  3.50187194]
 [ 0.          0.          2.26596132  4.2688381   6.67929945]
 [ 0.          0.          0.         11.49534556  5.74590548]
 [ 0.          0.          0.          0.          7.01714748]]


12. Задание
- создайте матрицу 5 на 5 заполненную нормальным распределением с парметрами среднее 10 и отклонение 2
- заполните все элементы на главной диагонали нулями

In [8]:
mask = np.random.normal(10, 2, (5,5))
np.fill_diagonal(mask, 0)

print(mask)

[[ 0.         13.03693356  8.78801168 10.01754459  9.08361603]
 [ 8.05666906  0.         13.72699202 10.79345868  9.89890479]
 [14.29876326  9.80398181  0.         12.13033643  6.58345871]
 [12.66589377 11.96527085 10.19919009  0.          8.37674351]
 [12.58833494 12.3561968   9.42686704  8.54595175  0.        ]]


13. Задание
- дано два массива, проверить одинаковы ли они

In [18]:
a = np.random.randint(0,2,5)
print(a)
b = np.random.randint(0,2,5)
print(b)
equal = np.array_equal(a, b)
equal

[0 1 0 1 0]
[0 0 1 0 1]


False

14. Задание
- сгенерируйте матрицу случайного размера:
 - строк от 3 до 7
 - столбцов от 2 до 12
- сгенерируйте число N - размер выборки так, чтобы оно не превышало половину количества элементов сгенерированной матрицы, но было больше 0
- сделайте случайную выборку N элементов

In [16]:
r, c = np.random.randint(3, 7), np.random.randint(2,12)
a = np.random.randint(-20,20,(r,c)) 
print(a)
N = (r * c)//2
print(N)
sample = np.random.choice(a.ravel(),size=N )
print(sample)

[[-12   8 -14  12 -16   3]
 [  7  -4 -11   5   2   0]
 [ 10  12 -16  -9   2 -18]
 [ -5  10 -17  15   8   8]
 [-11 -14  19  17   6   6]]
15
[ -5   3   8   8   8 -17   2   6   8 -14   8   6   8  -4 -12]


15. Задание
- дан вектор, проверить есть в нем Nan
- проверить есть в нем знак бесконечности
- заполнить их нулями

In [14]:
a = np.array([1, np.NaN, np.Inf], float)
print(a)
print(np.isnan(a))
print(np.isinf(a))
a = np.where(np.isnan(a) | np.isinf(a), 0, a)
a

[ 1. nan inf]
[False  True False]
[False False  True]


array([1., 0., 0.])

16. Задание
- сгенерировать массив с произвольным числом осей
- определить сколько у него осей

In [26]:
matrix =

<class 'SyntaxError'>: invalid syntax (<ipython-input-26-66415c5ac23d>, line 1)

17. Задание
- сгенерируйте матрицу 10 на 3 с нормальным распределением, среднее 50, отклонение 10
- найдите индексы максимальных элементов в каждой строке
- найдите сами элементы

In [22]:
matrix = np.random.normal(50, 10, (10,3))
print(matrix)
indexes = np.argmax(matrix, axis=1)
print(indexes)
print(np.amax(matrix, axis=1))

[[58.25906569 48.31170059 52.53408476]
 [51.05296905 52.37315558 47.89095483]
 [67.12803073 42.41539999 40.76421169]
 [51.34492875 55.05489071 53.60475124]
 [63.13586206 51.42074662 55.46247798]
 [45.57750299 54.23007597 45.3707665 ]
 [52.26580704 49.94203424 55.04086665]
 [46.97376983 67.18626141 49.48661174]
 [60.70755932 30.54283876 47.45861248]
 [48.07055666 69.5386048  33.5820917 ]]
[0 1 0 1 0 1 2 1 0 1]
[58.25906569 52.37315558 67.12803073 55.05489071 63.13586206 54.23007597
 55.04086665 67.18626141 60.70755932 69.5386048 ]
