In [1]:
import numpy as np

1. Задание
- проверьте тип объекта python_list
- если это не numpy ndarray, то преобразуйте к нему
- проверьте, что на выходе вы получили объект python_list желаемого типа

In [5]:
python_list = [1, 12, 13, 45, 76, 45, 98, 0]
print()
python_list = python_list if type(python_list) == "numpy.ndarray" \
    else np.array(python_list)
print()
type(python_list)

numpy.ndarray

2. Задание
- создайте одномерный массив numpy из 10 элементов заполненный числом 1.5

In [8]:
z = np.array([1.5 for _ in range(10)])
print(z)

[1.5 1.5 1.5 1.5 1.5 1.5 1.5 1.5 1.5 1.5]


3. Задание
- создайте двумерный массив numpy из 25 элементов заполненный числом 0

In [12]:
z = np.zeros(25)
print(z)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0.]


4. Задание
- создайте одномерный массив numpy из 12 элементов заполненный числом 1

In [13]:
ones = np.ones(12)
print(ones)

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


5. Задание
- преобразуйте массив из предыдущего задания к матрице 3 на 4
- выведите размерность полученного массива

In [16]:
ones = ones.reshape((3,4))
ones.shape

(3, 4)

6. Задание
- создайте матрицу 4 на 5 заполненную числами от 1 до 20
- замените элемент в 3-й строке 4-м столбце на -99

In [18]:
Z = np.arange(1, 21, 1).reshape(4,5)
print(Z)
Z[2, 3] = -99
print(Z)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]
[[  1   2   3   4   5]
 [  6   7   8   9  10]
 [ 11  12  13 -99  15]
 [ 16  17  18  19  20]]


7. Задание
- создайте вектор длинной 15 со случайными целыми числами в диапазоне от -10 до 10
- сделайте реверс вектора

In [20]:
first = np.random.randint(-10, 11, 15)
print(first)
second = first[::-1]
print(second)

[  9   1  -9  -4   9 -10   3   1  -7   7   8   7  -8  -9   8]
[  8  -9  -8   7   8   7  -7   1   3 -10   9  -4  -9   1   9]


8. Задание
- создайте матрицу 5 на 5 со случайными целыми числами в диапазоне от -15 до 15
- замените отрицательные элементы на их квадраты

In [34]:
first = np.random.randint(-15, 16, 25).reshape(5, 5)
print(first)
first = np.array([x ** 2 if x < 0 else x for x in first.flatten()]).reshape(5, 5)
print(first)

[[ 12 -15  -1 -11  13]
 [ 12  -8 -12  -3   1]
 [  6  -5 -15   3  -6]
 [ 15  12  10  -6 -14]
 [ -2   0 -10  14 -14]]
[[ 12 225   1 121  13]
 [ 12  64 144   9   1]
 [  6  25 225   3  36]
 [ 15  12  10  36 196]
 [  4   0 100  14 196]]


9. Задание
- создайте матрицу 3 на 5 со случайными целыми числами в диапазоне от -15 до 15
- найдите максимум и минимум
- найдите среднее по столбцам
- найдите среднее по строкам

In [39]:
first = np.random.randint(-15, 16, 15).reshape(3, 5)
print(first)
print("Max:", first.max())
print("Min:", first.min())
print("Avg_cols:", first.mean(axis=0))
print("Avg_rows:", first.mean(axis=1))

[[ -8   3  -7 -14  14]
 [ 14  -2  11  10   1]
 [ 15   3  -2 -11  -6]]
Max: 15
Min: -14
Avg_cols: [ 7.          1.33333333  0.66666667 -5.          3.        ]
Avg_rows: [-2.4  6.8 -0.2]


10. Задание
- даны две матрицы
- убедитесь, что их можно пермножить
- произведите операцию умножения матриц, если это возможно, иначе выведите ошибку

In [45]:
a = np.random.randint(-10, 10, (2, 5))
first_axis = np.random.randint(4, 6)
b = np.random.randint(-10, 10, (first_axis, 3))
if a.shape[1] == b.shape[0]:
    print(a.dot(b))
else:
    raise Exception()

[[  -5  -24  124]
 [ -19   56 -188]]


11. Задание
- создайте матрицу 5 на 5 заполненную равномерным распределением с диапазоно 2-12
- заполните все элементы ниже главной диагонали нулями

In [54]:
mask = np.random.uniform(2, 12, (5, 5))
print(mask)

matrix = np.copy(mask)
matrix[np.tril_indices(matrix.shape[0], -1)] = 0
print(matrix)

[[11.34527969  2.01466258 11.74243638 10.33842813 11.48963295]
 [ 4.62917535  4.5069499   5.53824699  5.35688835  2.13551617]
 [ 5.34957499 11.11617866  8.60974402  3.08627017 11.31107221]
 [ 8.58655168  7.32698461  4.28040029  4.99249972  8.13897787]
 [ 5.12864719  8.06178645  2.31779939  5.93053843  4.709031  ]]
[[11.34527969  2.01466258 11.74243638 10.33842813 11.48963295]
 [ 0.          4.5069499   5.53824699  5.35688835  2.13551617]
 [ 0.          0.          8.60974402  3.08627017 11.31107221]
 [ 0.          0.          0.          4.99249972  8.13897787]
 [ 0.          0.          0.          0.          4.709031  ]]


12. Задание
- создайте матрицу 5 на 5 заполненную нормальным распределением с парметрами среднее 10 и отклонение 2
- заполните все элементы на главной диагонали нулями

In [56]:
mask = np.random.normal(10, 2, (5, 5))
matrix = np.copy(mask)
matrix[np.diag_indices(mask.shape[0])] = 0
print(matrix)

[[ 0.         11.35101015  8.72700401 10.70494328 14.28039615]
 [11.28112684  0.         10.36182253  7.84065481  8.1533886 ]
 [11.0541833  13.41408266  0.         12.12184502 10.81467365]
 [12.2724768  10.94786634 11.69426005  0.          9.78443676]
 [10.92850546  9.04317546  7.82131952  7.68371555  0.        ]]


13. Задание
- дано два массива, проверить одинаковы ли они

In [58]:
a = np.random.randint(0,2,5)
print(a)
b = np.random.randint(0,2,5)
print(b)
equal = np.array_equal(a, b)
equal

[0 0 0 0 1]
[1 1 1 0 1]


False

14. Задание
- сгенерируйте матрицу случайного размера:
 - строк от 3 до 7
 - столбцов от 2 до 12
- сгенерируйте число N - размер выборки так, чтобы оно не превышало половину количества элементов сгенерированной матрицы, но было больше 0
- сделайте случайную выборку N элементов

In [60]:
r, c = (np.random.randint(3, 8), np.random.randint(2, 13))
a = np.random.sample((r, c))
print(a)
N = np.random.randint(1, r * c / 2)
print(N)
sample = np.random.choice(a.flatten(), N)
print(sample)

[[0.84373036 0.00397302 0.52309687 0.1018975  0.32168295 0.92905985
  0.7180733  0.07126375 0.20369508 0.67877644]
 [0.33073912 0.05107029 0.03593789 0.64748002 0.62716661 0.13137381
  0.27586571 0.43360165 0.83960686 0.79980386]
 [0.99700093 0.36933418 0.48857643 0.56709103 0.26452354 0.09897186
  0.52805588 0.94799276 0.71129171 0.92899743]
 [0.13356677 0.17532113 0.49374973 0.72863344 0.08648496 0.67612459
  0.96946029 0.76324935 0.86706841 0.38122644]]
10
[0.03593789 0.13356677 0.38122644 0.05107029 0.26452354 0.03593789
 0.99700093 0.08648496 0.72863344 0.03593789]


15. Задание
- дан вектор, проверить есть в нем Nan
- проверить есть в нем знак бесконечности
- заполнить их нулями

In [71]:
a = np.array([1, np.NaN, np.Inf], float)
a[np.isnan(a)] = 0
a[np.isinf(a)] = 0
a

array([1., 0., 0.])

16. Задание
- сгенерировать массив с произвольным числом осей
- определить сколько у него осей

In [87]:
axis = np.random.randint(2, 5, np.random.randint(2, 6))
print(axis)
matrix = np.random.sample(axis)
print(len(matrix.shape))

[2 3 4 4]
4


17. Задание
- сгенерируйте матрицу 10 на 3 с нормальным распределением, среднее 50, отклонение 10
- найдите индексы максимальных элементов в каждой строке
- найдите сами элементы

In [89]:
matrix = np.random.normal(50, 10, (10,3))
print(matrix)
indexes = np.argmax(matrix, axis=1)
print(indexes)
print([matrix[i, j] for i, j in enumerate(indexes)])

[[66.15597449 47.42057041 38.82998757]
 [55.84056188 15.50344143 48.74772998]
 [35.99536209 50.72372854 46.87417828]
 [46.94622747 76.11995598 44.219867  ]
 [33.83872696 48.41484734 54.11942771]
 [51.94068577 38.57115887 54.534821  ]
 [48.8739375  56.05043443 63.93989534]
 [65.37294656 55.52770359 65.04007844]
 [41.37469639 64.84316923 58.51511933]
 [51.90204023 47.10458827 51.72679914]]
[0 0 1 1 2 2 2 0 1 0]
[66.15597448735122, 55.84056187596195, 50.723728535502666, 76.11995597772992, 54.11942770890298, 54.534821004397706, 63.939895335125925, 65.37294655600674, 64.8431692250061, 51.90204023111272]
