In [0]:
import numpy as np

1. Задание
- проверьте тип объекта python_list
- если это не numpy ndarray, то преобразуйте к нему
- проверьте, что на выходе вы получили объект python_list желаемого типа

In [1]:
python_list = [1, 12, 13, 45, 76, 45, 98, 0]
print(type(python_list))
if type(python_list) != type(np.array([1,2,3])):
    python_list = np.array([1, 12, 13, 45, 76, 45, 98, 0])
print(type(python_list))

<class 'list'>
<class 'numpy.ndarray'>


2. Задание
- создайте одномерный массив numpy из 10 элементов заполненный числом 1.5

In [2]:
z = np.array([1.5 for i in range(10)])
print(z)

[1.5 1.5 1.5 1.5 1.5 1.5 1.5 1.5 1.5 1.5]


3. Задание
- создайте двумерный массив numpy из 25 элементов заполненный числом 0

In [3]:
z = np.zeros((5, 5))
print(z)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


4. Задание
- создайте одномерный массив numpy из 12 элементов заполненный числом 1

In [4]:
ones = np.ones(12, int)
print(ones)

[1 1 1 1 1 1 1 1 1 1 1 1]


5. Задание
- преобразуйте массив из предыдущего задания к матрице 3 на 4
- выведите размерность полученного массива

In [5]:
ones = ones.reshape(3,4)
print(ones.shape)

(3, 4)


6. Задание
- создайте матрицу 4 на 5 заполненную числами от 1 до 20
- замените элемент в 3-й строке 4-м столбце на -99

In [6]:
Z = np.arange(1, 21).reshape((4, 5))
print(Z)
Z[2,3] = -99
print(Z)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]
[[  1   2   3   4   5]
 [  6   7   8   9  10]
 [ 11  12  13 -99  15]
 [ 16  17  18  19  20]]


7. Задание
- создайте вектор длинной 15 со случайными целыми числами в диапазоне от -10 до 10
- сделайте реверс вектора

In [7]:
first = np.random.randint(-10, 10, 15)
print(first)
second = first[::-1]
print(second)

[  1   8   1   9   4   2  -6   1 -10  -5  -2   2   8  -9   2]
[  2  -9   8   2  -2  -5 -10   1  -6   2   4   9   1   8   1]


8. Задание
- создайте матрицу 5 на 5 со случайными целыми числами в диапазоне от -15 до 15
- замените отрицательные элементы на их квадраты

In [8]:
first = np.random.randint(-15, 15, 25).reshape(5,5)
print(first)
first = np.where(first < 0, first ** 2, first)
print(first)

[[ -1   4  12  13   5]
 [ -4   8 -13   3   8]
 [ -3  -7  -8 -14   5]
 [ 11 -10   2 -11   8]
 [  0 -13  13  -8 -12]]
[[  1   4  12  13   5]
 [ 16   8 169   3   8]
 [  9  49  64 196   5]
 [ 11 100   2 121   8]
 [  0 169  13  64 144]]


9. Задание
- создайте матрицу 3 на 5 со случайными целыми числами в диапазоне от -15 до 15
- найдите максимум и минимум
- найдите среднее по столбцам
- найдите среднее по строкам

In [9]:
first = np.random.randint(-15, 15, 15).reshape(3,5)
print(first)
print(first.max())
print(first.min())
print(np.mean(first, axis=0))
print(np.mean(first, axis=1, keepdims = True))

[[  6  -1   2   4   9]
 [  6 -15 -11   2  -1]
 [  3   6  -1  -4  11]]
11
-15
[ 5.         -3.33333333 -3.33333333  0.66666667  6.33333333]
[[ 4. ]
 [-3.8]
 [ 3. ]]


10. Задание
- даны две матрицы
- убедитесь, что их можно пермножить
- произведите операцию умножения матриц, если это возможно, иначе выведите ошибку

In [10]:
a = np.random.randint(-10, 10, (2, 5))
first_axis = np.random.randint(4, 6)
b = np.random.randint(-10, 10, (first_axis, 3))
if a.shape[1] == b.shape[0]:
    print(a @ b)
else:
    raise Exception('Матрицы не согласованы')

[[-14  23 114]
 [-12 -24  79]]


11. Задание
- создайте матрицу 5 на 5 заполненную равномерным распределением с диапазоно 2-12
- заполните все элементы ниже главной диагонали нулями

In [11]:
mask = np.random.uniform(2, 12, (5, 5))
matrix = np.triu(mask)

print(matrix)

[[8.25038355 6.08825806 3.16237398 2.28191764 3.33556773]
 [0.         4.9366809  6.9472132  4.23223229 9.86861145]
 [0.         0.         6.50718322 9.88483789 8.81063026]
 [0.         0.         0.         6.533728   7.96559933]
 [0.         0.         0.         0.         7.51449851]]


12. Задание
- создайте матрицу 5 на 5 заполненную нормальным распределением с парметрами среднее 10 и отклонение 2
- заполните все элементы на главной диагонали нулями

In [12]:
matrix = np.random.uniform(10, 2, (5, 5))
np.fill_diagonal(matrix, 0)

print(matrix)

[[0.         3.46280477 4.20558853 6.45725307 2.69067203]
 [7.12653369 0.         6.44202366 2.50661627 2.0254555 ]
 [8.80324417 9.95471846 0.         7.43085754 6.38382735]
 [3.31048899 9.81316014 5.91944475 0.         8.63145251]
 [3.1321131  8.55712022 7.50059044 2.02695731 0.        ]]


13. Задание
- дано два массива, проверить одинаковы ли они

In [13]:
a = np.random.randint(0,2,5)
print(a)
b = np.random.randint(0,2,5)
print(b)
#equal = a == b => equal.all() или np.equal(a, b).all()
equal = np.array_equal(a, b)
equal

[1 0 0 0 1]
[1 1 1 0 1]


False

14. Задание
- сгенерируйте матрицу случайного размера:
 - строк от 3 до 7
 - столбцов от 2 до 12
- сгенерируйте число N - размер выборки так, чтобы оно не превышало половину количества элементов сгенерированной матрицы, но было больше 0
- сделайте случайную выборку N элементов

In [14]:
r, c = np.random.randint([3, 2], [7, 12])
a = np.random.randint(1, 15, (r, c))
print(a)
N = np.random.randint(1, (r*c)/2)
print(N)
sample = np.random.choice(a.flatten(), N)
print(sample)

[[14  1 14  8  3 11  7 10  3]
 [ 6  7  4  7  5  5  3 14  2]
 [ 1  2 11  5 10  8  3  7  3]
 [ 6  1 13  8  9 11  5  7  1]]
8
[ 3 11 10  3  2  2  5  7]


15. Задание
- дан вектор, проверить есть в нем Nan
- проверить есть в нем знак бесконечности
- заполнить их нулями

In [15]:
a = np.array([1, np.NaN, np.Inf], float)
print(np.isnan(a).any())
print(np.isinf(a).any())
a[np.isnan(a)] = 0.
a[np.isinf(a)] = 0.
print(a)

True
True
[1. 0. 0.]


16. Задание
- сгенерировать массив с произвольным числом осей
- определить сколько у него осей

In [16]:
axis = np.random.randint(1, 15)
print(axis)
matrix = np.zeros(range(axis))
print(matrix.ndim)

3
3


17. Задание
- сгенерируйте матрицу 10 на 3 с нормальным распределением, среднее 50, отклонение 10
- найдите индексы максимальных элементов в каждой строке
- найдите сами элементы

In [17]:
matrix = np.random.normal(50, 10, (10,3))
print(matrix)
indexes = np.argmax(matrix, 1)
print(indexes)
print(matrix[range(matrix.shape[0]), indexes])

[[50.94747793 42.91001562 54.84269122]
 [47.42321719 50.99581998 59.70228688]
 [51.68759433 52.10665795 27.19269554]
 [36.41076644 55.63482713 40.28882282]
 [37.82787003 47.03523973 73.10854609]
 [62.57896407 57.83790414 65.86469857]
 [48.36785779 53.27431004 61.46946736]
 [54.45003777 55.66186162 29.65398427]
 [46.12617365 66.8101111  34.61421603]
 [58.65697598 38.72072121 45.39562589]]
[2 2 1 1 2 2 2 1 1 0]
[54.84269122 59.70228688 52.10665795 55.63482713 73.10854609 65.86469857
 61.46946736 55.66186162 66.8101111  58.65697598]
